window.CASE_FILE_CONFIG={
title:"The Pharaoh's Secret",caseNumber:"03",location:"Valley of the Kings · Tomb KV62",
brief:"Tutankhamun ruled Egypt for only about nine years and died young. Yet after Howard Carter and an Egyptian excavation team uncovered his tomb in 1922, the little-known king became the most famous pharaoh in the world.",
question:"Why did Tutankhamun become far more famous after death than during his reign?",
assignment:"Use archaeology, tomb design, preservation, objects, and modern documentation to separate ancient importance from modern fame.",
midCaseTwist:{icon:"🏺",title:"Small Tomb. Huge Discovery.",text:"The tomb was modest compared with many royal burials, but it survived substantially intact. The case is shifting from 'How powerful was Tutankhamun?' to 'Why did preservation change his historical legacy?'"},
crossExam:{question:"Which statement best explains Tutankhamun's modern fame?",choices:["He ruled Egypt longer than almost every other pharaoh.","His substantially intact tomb preserved thousands of objects that could be studied, photographed, and shared with the world.","His tomb was the largest ever built in the Valley of the Kings.","He was unknown until the 2000s."],answer:1,explain:"The unusual survival of the tomb and its objects created an extraordinary archaeological record. Modern documentation transformed that record into global fame."},
closingCaution:"Tutankhamun's fame today reflects archaeology and preservation as much as his political importance in ancient Egypt. A spectacular discovery can reshape which people from the past become culturally famous.",
evidence:[
{id:"e1",num:"Evidence 01",title:"A Short Reign",date:"18th Dynasty · c. 1336–1327 BCE",sourceType:"Royal Record",text:"Museum records place Tutankhamun's reign at roughly nine years. He came to the throne young and died before becoming one of Egypt's long-reigning rulers.",observation:"His ancient political career was relatively brief.",question:"What does the short reign suggest about his later fame?",choices:["His modern fame cannot simply be explained by an exceptionally long reign.","It proves he built every major monument in Egypt.","It proves he was the most powerful pharaoh ever.","It means no records of his reign survive."],answer:0,explain:"A short reign makes it less likely that duration of rule alone explains his exceptional modern fame."},
{id:"e2",num:"Evidence 02",title:"A Modest Royal Tomb",date:"Valley of the Kings · KV62",sourceType:"Archaeology",text:"Egypt's Ministry of Tourism and Antiquities describes Tutankhamun's tomb as modest in size and decoration compared with the larger tombs of powerful New Kingdom kings.",observation:"The burial space itself was not unusually grand for a royal tomb.",question:"What does this file challenge?",choices:["The idea that Tutankhamun is famous because he had the largest royal tomb.","The fact that he was a pharaoh.","The existence of the Valley of the Kings.","The discovery date of 1922."],answer:0,explain:"The tomb's modest scale makes its later fame even more dependent on preservation and contents."},
{id:"e3",num:"Evidence 03",title:"Substantially Intact",date:"Discovery · November 1922",sourceType:"Archaeology",text:"The British Museum and Egyptian antiquities authorities describe KV62 as the only New Kingdom royal tomb found substantially intact.",observation:"Unlike many royal tombs, much of the burial assemblage survived for archaeologists to document.",question:"Why is preservation so important?",choices:["It gave archaeologists a rare, unusually complete royal burial assemblage.","It proves no one entered the tomb in antiquity.","It means the tomb had no damage at all.","It proves Tutankhamun had the longest reign."],answer:0,explain:"Substantially intact does not mean untouched, but it does mean the surviving evidence was extraordinarily rich."},
{id:"e4",num:"Evidence 04",title:"More Than 5,000 Objects",date:"Excavation · 1920s",sourceType:"Artifact Record",text:"The Metropolitan Museum of Art notes that more than 5,000 objects were found in the tomb and required years of recording and conservation.",observation:"The discovery preserved a vast collection of royal funerary objects in context.",question:"What did the quantity of objects make possible?",choices:["Detailed study of royal burial practices, craftsmanship, and material culture.","Proof that every pharaoh was buried exactly the same way.","Proof that Tutankhamun personally made the objects.","Evidence that the tomb was empty."],answer:0,explain:"A large assemblage in context gives historians and archaeologists far more evidence than isolated objects."},
{id:"e5",num:"Evidence 05",title:"The Camera Entered the Tomb",date:"Documentation · 1920s–1930s",sourceType:"Photography",text:"The Metropolitan Museum's photographer Harry Burton produced extensive photographs of the tomb, objects, and excavation process over many years.",observation:"The discovery was not only excavated; it was visually documented and made accessible to a worldwide audience.",question:"Why does documentation matter to historical fame?",choices:["It allowed the discovery to circulate far beyond the excavation site.","It made archaeology unnecessary.","It proves every photograph is unbiased.","It means the objects never needed conservation."],answer:0,explain:"Photography helped turn an archaeological discovery into a global visual event."},
{id:"e6",num:"Evidence 06",title:"A Worldwide Sensation",date:"Public response · 1922 onward",sourceType:"Public History",text:"The British Museum describes the discovery as a sensation that generated enormous public interest in Egyptology and the 'boy king.'",observation:"Modern media and public fascination amplified the archaeological discovery into a lasting cultural phenomenon.",question:"What does this evidence add to the case?",choices:["Modern fame was created through both archaeology and public culture.","Ancient Egyptians used modern newspapers to promote him.","The tomb mattered only to archaeologists.","The discovery had little public impact."],answer:0,explain:"Historical fame is shaped not only by what happened in the past, but also by what later societies discover, preserve, and publicize."}
],
theories:[
{id:"preservation",title:"Preservation Created the Modern Icon",desc:"Tutankhamun became famous because an unusually intact burial assemblage survived and was documented in extraordinary detail.",strong:["e2","e3","e4","e5","e6"],weak:["e1"],summary:"This explanation best fits the modest tomb, exceptional preservation, thousands of objects, extensive photography, and global public response."},
{id:"power",title:"Ancient Power Alone Explains His Fame",desc:"Tutankhamun is famous mainly because he was one of Egypt's longest-ruling and most powerful kings.",strong:[],weak:["e1","e2","e3","e4","e5","e6"],summary:"The evidence does not support a long reign or an unusually monumental tomb. His modern fame is much greater than his surviving record of political power."},
{id:"size",title:"The Largest Tomb Made Him Famous",desc:"His tomb became famous because it was the biggest and most elaborate royal tomb in the valley.",strong:[],weak:["e2","e3","e4"],summary:"This theory conflicts with official descriptions of KV62 as relatively modest in size and decoration."},
{id:"media",title:"Modern Media Alone Created the Fame",desc:"The tomb itself was ordinary; publicity alone made Tutankhamun famous.",strong:["e5","e6"],weak:["e3","e4"],summary:"Media mattered, but publicity had extraordinary material to work with: a substantially intact royal tomb containing thousands of objects."}
],
sources:[
{label:"British Museum — Tutankhamun: Ancient and Modern Perspectives",url:"https://www.britishmuseum.org/visit/object-trails/tutankhamun-ancient-and-modern-perspectives"},
{label:"Metropolitan Museum — Discovering Tutankhamun",url:"https://www.metmuseum.org/exhibitions/listings/2006/discovering-tutankhamun"},
{label:"Egypt Ministry of Tourism & Antiquities — Tomb of Tutankhamun",url:"https://egymonuments.gov.eg/en/monuments/tomb-of-tutankhamun"}
]};