window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Activists",brief:"Identify activists from the movements, strategies, writings, organizations, and reforms connected to their work.",question:"Can you identify the activist before all three clues are revealed?",
people:[
{name:"Frederick Douglass",roundTitle:"Identity 1 · Abolition",clues:["I escaped slavery and became a powerful public speaker.","My 1845 autobiography became a major antislavery text.","I also advocated women's rights and Black citizenship."],options:["Frederick Douglass","William Lloyd Garrison","Booker T. Washington","W. E. B. Du Bois"],answer:0,explain:"Douglass used speeches, newspapers, autobiography, and political advocacy against slavery and racial inequality."},
{name:"Sojourner Truth",roundTitle:"Identity 2 · Abolition and Women's Rights",clues:["I was born enslaved in New York and later secured my freedom.","I became a traveling speaker for abolition and women's rights.","My public memory is closely linked to an 1851 women's-rights convention in Ohio."],options:["Harriet Tubman","Sojourner Truth","Lucretia Mott","Ida B. Wells"],answer:1,explain:"Truth connected antislavery activism with advocacy for women's rights and equality."},
{name:"Ida B. Wells",roundTitle:"Identity 3 · Investigative Activism",clues:["I was a journalist and activist born in Mississippi.","I documented and campaigned against lynching in the United States.","I also participated in women's suffrage and civil-rights organizing."],options:["Ida B. Wells","Mary Church Terrell","Frances Harper","Fannie Lou Hamer"],answer:0,explain:"Wells combined investigative journalism, statistical evidence, speaking, and organizing in her anti-lynching campaign."},
{name:"Emmeline Pankhurst",roundTitle:"Identity 4 · Votes for Women",clues:["I was a British political activist.","I helped found the Women's Social and Political Union.","My organization became known for militant tactics in the campaign for women's suffrage."],options:["Emmeline Pankhurst","Millicent Fawcett","Susan B. Anthony","Elizabeth Cady Stanton"],answer:0,explain:"Pankhurst became one of the most recognizable leaders of Britain's militant suffrage movement."},
{name:"César Chávez",roundTitle:"Identity 5 · Farmworker Organizing",clues:["I organized agricultural workers in the United States.","I co-founded the organization that became the United Farm Workers.","Boycotts, marches, and nonviolent organizing became central to my public work."],options:["César Chávez","Dolores Huerta","A. Philip Randolph","Bayard Rustin"],answer:0,explain:"Chávez helped build a national farmworker movement around union organizing and consumer boycotts."}
],
closing:"Activists convert grievances into organization. Their impact depends on networks of supporters, strategy, communication, evidence, and sustained pressure.",
takeaways:["Movements are larger than individual leaders.","Print and journalism can become tools of activism.","Direct action and legal reform often interact.","Activists frequently work across more than one cause."]
};