window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Inventors",brief:"Identify innovators from the problems they tackled, the technologies associated with them, and the historical context around their work.",question:"Can you identify the inventor before all three clues are revealed?",
people:[
{name:"Johannes Gutenberg",roundTitle:"Identity 1 · Print Revolution",clues:["I worked in Mainz in the 15th century.","I developed a European system of movable metal type and a press suited to mass book production.","My name is strongly associated with the Gutenberg Bible."],options:["Johannes Gutenberg","Alexander Graham Bell","Thomas Edison","James Watt"],answer:0,explain:"Gutenberg's printing system helped make large-scale book production faster and more economical in Europe."},
{name:"Alexander Graham Bell",roundTitle:"Identity 2 · Voice Across Distance",clues:["I worked on technologies connected to speech and sound.","In 1876 I received a famous U.S. patent connected to transmitting speech electrically.","My name is closely associated with the early telephone."],options:["Samuel Morse","Alexander Graham Bell","Nikola Tesla","Guglielmo Marconi"],answer:1,explain:"Bell became one of the figures most closely associated with the development and commercialization of the telephone."},
{name:"Thomas Edison",roundTitle:"Identity 3 · The Invention Laboratory",clues:["I built a large research laboratory at Menlo Park.","My work involved sound recording, electric lighting, and power systems.","The phonograph became one of my best-known inventions."],options:["Thomas Edison","George Eastman","Eli Whitney","Michael Faraday"],answer:0,explain:"Edison's laboratory model organized teams around practical invention and commercialization."},
{name:"The Wright Brothers",roundTitle:"Identity 4 · Controlled Flight",clues:["We operated a bicycle business before becoming aviation experimenters.","We tested gliders and focused heavily on control as well as lift.","In 1903 our powered aircraft flew at Kitty Hawk."],options:["Montgolfier Brothers","Wright Brothers","Lumière Brothers","Grimm Brothers"],answer:1,explain:"Wilbur and Orville Wright achieved controlled, sustained powered flight in 1903."},
{name:"Hedy Lamarr",roundTitle:"Identity 5 · Signals and Secrecy",clues:["I was also a famous film actor.","During World War II I co-developed a frequency-hopping communication concept with George Antheil.","Later generations connected that idea to spread-spectrum communication technologies."],options:["Grace Hopper","Hedy Lamarr","Ada Lovelace","Marie Curie"],answer:1,explain:"Lamarr and Antheil patented a frequency-hopping system intended to make radio-controlled torpedoes harder to jam."}
],
closing:"Inventors rarely work outside their historical context. Problems, materials, previous discoveries, collaboration, patents, business, and institutions all shape what becomes an invention.",
takeaways:["Invention often improves existing ideas.","Commercialization can matter as much as invention.","Teams and laboratories changed how innovation was organized.","A person's public fame may hide other important work."]
};