window.ESCAPE_CONFIG={
title:"Escape the Plantation",brief:"This mission reconstructs historical decisions involved in self-emancipation from slavery in the nineteenth-century United States. It is designed as an evidence exercise, not entertainment built around suffering.",
objectiveTitle:"Reconstruct a Freedom Route",objective:"Use law, geography, secrecy, and documented Underground Railroad evidence to identify the safest historical choices available in a dangerous system.",
sensitivityNote:"This game treats slavery as a system of violence and coercion. The player is analyzing historical evidence about self-emancipation rather than role-playing enslavement for amusement.",
stages:[
{type:"choice",title:"The First Decision",scene:"The route begins with a basic question: who drives an escape from slavery?",clueTitle:"Clue: Self-Emancipation",clue:"National Park Service interpretation emphasizes that many freedom seekers planned and carried out their own escapes. Assistance networks could matter greatly, but escape began with the decisions and agency of enslaved people themselves.",hint:"Center the freedom seeker, not the helper.",question:"Which statement best fits the evidence?",choices:["Freedom seekers were central actors in planning and carrying out escape.","Escape depended entirely on white conductors.","Every escape followed the same organized route.","Most freedom seekers waited passively to be rescued."],answer:0,wrong:"The historical framework centers self-emancipation and agency.",danger:12,reward:{icon:"🧭",item:"Route Decision",note:"Agency begins the escape process."},explain:"The Underground Railroad is best understood as resistance through self-emancipation, sometimes aided by wider networks."},
{type:"code",title:"The Law Barrier",scene:"A legal notice changes the risk of travel even in northern states.",clueTitle:"Clue: Fugitive Slave Act",clue:"The Fugitive Slave Act of 1850 strengthened federal mechanisms for capturing alleged freedom seekers and increased danger in free states.",hint:"Enter the year of the law named in the clue.",question:"Enter the year.",answer:"1850",numeric:true,placeholder:"4-digit year",wrong:"The year is stated directly in the clue.",danger:12,reward:{icon:"📜",item:"Law Warning",note:"Legal danger extends beyond slave states."},explain:"The 1850 law made northern destinations less secure and influenced decisions to continue toward Canada or other destinations."},
{type:"sequence",title:"The Route Logic",scene:"A successful route requires careful order: understand the law, identify geography, secure trusted help when available, and keep moving toward safety.",clueTitle:"Clue: No Single Railroad",clue:"There was no one fixed Underground Railroad route. Freedom seekers adapted to local geography, legal danger, trusted contacts, transportation, and changing opportunities.",hint:"Choose the order that starts with assessing risk and ends with reaching a safer destination.",question:"Tap the decisions in a logical order.",items:["Assess legal and geographic risk","Identify a route or trusted contact","Move using secrecy and local knowledge","Reach a safer destination and reassess"],answer:[0,1,2,3],wrong:"Start with risk and planning before movement.",danger:14,reward:{icon:"🗺️",item:"Route Map",note:"There was no single fixed escape route."},explain:"Escape routes were adaptive, local, and dependent on changing conditions rather than one national map."},
{type:"choice",title:"The Myth Check",scene:"The final route is blocked by a popular story that may not be supported by evidence.",clueTitle:"Clue: Quilt Codes",clue:"The National Park Service notes that researchers have not found first-hand documentary evidence for the popular claim that a standardized quilt code guided freedom seekers along the Underground Railroad.",hint:"A repeated story is not automatically a documented historical practice.",question:"How should a historian treat the quilt-code claim?",choices:["As a later story that lacks documented first-hand support.","As proven because it appears in modern popular culture.","As the main navigation system used by Harriet Tubman.","As more reliable than contemporary evidence."],answer:0,wrong:"Historical method distinguishes folklore from documented practice.",danger:12,reward:{icon:"🔎",item:"Myth Check",note:"Separates documented evidence from later folklore."},explain:"The stronger interpretation is to say that the quilt-code story is not supported by known first-hand evidence."}
],
finalLock:{icon:"🕯️",question:"What is the strongest overall interpretation of the Underground Railroad?",choices:["A flexible pattern of self-emancipation and assistance shaped by geography, law, secrecy, and local networks.","A single national organization with one fixed route.","A system run entirely by Harriet Tubman.","A network whose methods are completely documented."],answer:0,wrong:"Use all four evidence items together.",explain:"The historical record points to a decentralized movement centered on freedom seekers and adapted to local conditions."},
closing:"The mission ends with a more accurate picture of the Underground Railroad: not a single route, not one organization, and not a story of passive rescue, but a history of self-emancipation, risk, adaptation, and assistance.",
takeaways:["Freedom seekers were central historical actors.","The 1850 Fugitive Slave Act increased danger.","Routes varied by geography and circumstance.","Popular stories should be separated from documented evidence."],
sources:[{label:"NPS — Underground Railroad",url:"https://www.nps.gov/subjects/undergroundrailroad/index.htm"},{label:"NPS — Frequently Asked Questions",url:"https://www.nps.gov/subjects/undergroundrailroad/frequently-asked-questions.htm"}]
};