window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Explorers",brief:"Identify explorers from routes, sponsors, voyages, encounters, and the larger systems of trade, empire, science, and colonization surrounding their journeys.",question:"Can you identify the explorer before all three clues are revealed?",
people:[
{name:"Zheng He",roundTitle:"Identity 1 · Indian Ocean Voyages",clues:["I commanded enormous Ming dynasty fleets in the early 15th century.","My voyages reached Southeast Asia, South Asia, Arabia, and East Africa.","I sailed under the Yongle emperor."],options:["Zheng He","Ibn Battuta","Xuanzang","Marco Polo"],answer:0,explain:"Zheng He's state-sponsored voyages projected Ming prestige across the Indian Ocean world."},
{name:"Ibn Battuta",roundTitle:"Identity 2 · Across the Islamic World",clues:["I was a Moroccan traveler born in Tangier.","I traveled across North Africa, the Middle East, East Africa, Central Asia, South Asia, and beyond.","My journeys were later recorded in the Rihla."],options:["Ibn Battuta","Zheng He","Al-Idrisi","Leo Africanus"],answer:0,explain:"Ibn Battuta's travels provide an extraordinary record of the 14th-century Afro-Eurasian world."},
{name:"Christopher Columbus",roundTitle:"Identity 3 · Atlantic Crossing",clues:["I sailed west across the Atlantic under Spanish sponsorship in 1492.","My voyage reached islands in the Caribbean.","My voyages intensified sustained contact between Europe and the Americas, with enormous consequences for Indigenous peoples."],options:["Vasco da Gama","Christopher Columbus","Ferdinand Magellan","Amerigo Vespucci"],answer:1,explain:"Columbus's voyages began sustained Spanish colonization in the Caribbean and accelerated the Columbian Exchange."},
{name:"Vasco da Gama",roundTitle:"Identity 4 · Sea Route to India",clues:["I was a Portuguese navigator.","I rounded the Cape of Good Hope and reached India by sea.","My 1497–1499 voyage helped connect Portugal directly to Indian Ocean trade routes."],options:["Bartolomeu Dias","Vasco da Gama","Pedro Cabral","Henry the Navigator"],answer:1,explain:"Da Gama's voyage established a direct sea route between Portugal and India around Africa."},
{name:"Sacagawea",roundTitle:"Identity 5 · Across the North American West",clues:["I was a Lemhi Shoshone woman.","I traveled with the Lewis and Clark expedition while carrying my infant son.","My language knowledge, regional familiarity, and presence helped the expedition communicate and move through western North America."],options:["Sacagawea","Pocahontas","Sarah Winnemucca","Nanyehi"],answer:0,explain:"Sacagawea contributed translation, geographic knowledge, food gathering, and diplomatic value to the expedition."}
],
closing:"Exploration is never simply discovery. Voyages happen within worlds already inhabited, mapped, traded through, and understood by local peoples.",
takeaways:["Sponsors shape the purpose of voyages.","Indigenous knowledge often made expeditions possible.","Exploration can expand trade and empire simultaneously.","The language of discovery should be used carefully."]
};