window.MAP_QUEST_CONFIG={
title:"Empire Mapper",brief:"Empires are shaped by geography. Rivers, mountain chains, deserts, seas, roads, and strategic chokepoints can help states expand—and limit how far they can control.",
question:"Use geographic clues to identify the empire or region that best fits each map problem.",
rounds:[
{title:"Mediterranean Power",prompt:"Find the empire whose core geography turned the Mediterranean into a major internal highway.",clueTitle:"Clue: Mare Nostrum",clue:"This empire expanded around the Mediterranean basin, linking Italy, North Africa, Iberia, Greece, and the eastern Mediterranean through roads and sea lanes.",places:[{name:"Roman Empire",detail:"Mediterranean basin"},{name:"Inca Empire",detail:"Andes"},{name:"Mali Empire",detail:"West Africa"},{name:"Mughal Empire",detail:"South Asia"}],answer:0,explain:"Roman power depended heavily on Mediterranean shipping, coastal cities, roads, and control of strategic territory around the sea."},
{title:"Mountain Empire",prompt:"Choose the empire whose infrastructure adapted to one of the world's longest mountain systems.",clueTitle:"Clue: High Roads",clue:"This empire connected valleys, highlands, storehouses, and administrative centers with a vast road network across the Andes.",places:[{name:"Ottoman Empire",detail:"Anatolia and Balkans"},{name:"Inca Empire",detail:"Andean South America"},{name:"Achaemenid Persia",detail:"Southwest Asia"},{name:"Song China",detail:"East Asia"}],answer:1,explain:"The Inca state used roads, bridges, runners, and storehouses to govern difficult Andean terrain."},
{title:"Gold and Desert Routes",prompt:"Identify the empire positioned to benefit from trade between West African gold regions and Saharan caravan routes.",clueTitle:"Clue: Sahel Crossroads",clue:"This empire grew along the Niger River and profited from long-distance exchange in gold, salt, and other goods across the Sahara.",places:[{name:"Mali Empire",detail:"West African Sahel"},{name:"Byzantine Empire",detail:"Eastern Mediterranean"},{name:"Aztec Empire",detail:"Central Mexico"},{name:"Mauryan Empire",detail:"South Asia"}],answer:0,explain:"Mali's location connected Niger River communities with trans-Saharan caravan routes and gold-producing regions."},
{title:"The Bosporus Gate",prompt:"Find the empire whose capital controlled the strait linking the Black Sea and Mediterranean.",clueTitle:"Clue: Strategic Chokepoint",clue:"After conquering Constantinople, this empire controlled a city positioned between Europe and Asia and beside one of the world's most important maritime chokepoints.",places:[{name:"Ottoman Empire",detail:"Balkans, Anatolia, eastern Mediterranean"},{name:"Mali Empire",detail:"West Africa"},{name:"Inca Empire",detail:"Andes"},{name:"Han Empire",detail:"East Asia"}],answer:0,explain:"Ottoman control of Constantinople/Istanbul and the Bosporus gave the empire major strategic and commercial advantages."}
],
challenge:{question:"Which statement best explains why geography matters to empires?",choices:["Geography guarantees that an empire will rise.","Geography shapes opportunities and limits, but rulers still need institutions, resources, military power, and political choices.","Only coastal empires depend on geography.","Mountains and deserts always prevent expansion."],answer:1,explain:"Geography creates possibilities and constraints; it does not determine history by itself."},
closing:"Empire maps become more meaningful when territory is connected to terrain, trade, transport, resources, and chokepoints.",
takeaways:["Seas can connect rather than divide.","Mountain states need specialized infrastructure.","Trade geography can finance political power.","Strategic chokepoints can magnify the value of a city or region."]
};