window.ESCAPE_CONFIG={
title:"Escape the Cold War Bunker",brief:"The bunker is filled with intelligence files from the Cold War: blockade maps, missile alerts, alliance documents, and crisis communications. The challenge is to distinguish deterrence, escalation, signaling, and diplomacy.",
objectiveTitle:"Prevent Escalation",objective:"Solve four Cold War locks, recover intelligence files, and use them to choose the safest final interpretation before the bunker seals.",
stages:[
{type:"choice",title:"The Berlin File",scene:"A map shows West Berlin inside the Soviet occupation zone and air corridors leading from western Germany.",clueTitle:"Clue: Berlin Blockade and Airlift",clue:"In 1948, the Soviet Union blocked western land access to West Berlin. The United States and its allies responded with a large airlift rather than abandoning the city or immediately using force.",hint:"Look for a response that resisted pressure without starting a direct war.",question:"What did the airlift demonstrate?",choices:["A non-shooting way to sustain West Berlin while avoiding immediate military confrontation.","That Berlin had no strategic importance.","That the Cold War had already become a direct U.S.-Soviet war.","That aircraft played no role in postwar Europe."],answer:0,wrong:"Focus on how the response balanced resistance with escalation control.",danger:12,reward:{icon:"✈️",item:"Airlift Corridor Map",note:"Evidence of pressure without direct war."},explain:"The airlift sustained West Berlin while avoiding a ground confrontation with Soviet forces."},
{type:"code",title:"The Missile Alert",scene:"An intelligence summary identifies the year of the Cuban Missile Crisis.",clueTitle:"Clue: Thirteen Days",clue:"The Cuban Missile Crisis occurred in October 1962 after U.S. reconnaissance identified Soviet nuclear missile sites in Cuba.",hint:"Enter the year in the clue.",question:"Enter the year of the Cuban Missile Crisis.",answer:"1962",numeric:true,placeholder:"4-digit year",wrong:"The date is stated directly in the clue.",danger:10,reward:{icon:"☢️",item:"Missile Alert",note:"Marks one of the most dangerous Cold War crises."},explain:"The 1962 crisis brought the superpowers extraordinarily close to direct nuclear confrontation."},
{type:"sequence",title:"The Crisis Room",scene:"A decision board shows a simplified sequence from discovery to resolution during the Cuban Missile Crisis.",clueTitle:"Clue: Pressure and Communication",clue:"U.S. leaders discovered the missiles, imposed a naval quarantine, exchanged messages with Soviet leaders, and reached an agreement that removed the missiles while providing security assurances.",hint:"Put the broad sequence in chronological order.",question:"Tap the stages in order.",items:["Missile sites are identified","Naval quarantine is announced","Leaders exchange crisis messages","Settlement removes missiles and reduces immediate threat"],answer:[0,1,2,3],wrong:"Begin with discovery, then pressure, communication, and settlement.",danger:14,reward:{icon:"📡",item:"Crisis Communications File",note:"Shows how signaling and diplomacy interacted."},explain:"The crisis moved through intelligence, coercive pressure, communication, and negotiated de-escalation."},
{type:"choice",title:"The Deterrence Console",scene:"A strategy memo explains why nuclear powers avoided direct war even while building massive arsenals.",clueTitle:"Clue: Deterrence",clue:"Nuclear deterrence rested on the belief that a devastating retaliatory strike could make a first attack irrational. This logic depended on credible second-strike capability and carried enormous risks of miscalculation.",hint:"Deterrence tries to prevent attack by threatening unacceptable retaliation.",question:"What is the core logic of nuclear deterrence?",choices:["Convince an opponent that attacking would trigger unacceptable retaliation.","Guarantee that accidents and miscalculation are impossible.","Make diplomacy unnecessary.","Ensure that nuclear weapons will definitely be used."],answer:0,wrong:"Focus on preventing attack through the threat of retaliation.",danger:12,reward:{icon:"🛰️",item:"Deterrence Memo",note:"Explains strategic restraint through retaliatory capability."},explain:"Deterrence aimed to prevent attack by making the expected cost of aggression catastrophically high."}
],
finalLock:{icon:"🚨",question:"What is the strongest interpretation of Cold War crisis management?",choices:["Military pressure, deterrence, communication, and diplomacy all interacted—and success depended on limiting escalation as well as showing resolve.","The superpowers avoided war because there were no serious confrontations.","Nuclear weapons made diplomacy irrelevant.","Every crisis was fully controlled by leaders."],answer:0,wrong:"Combine Berlin, Cuba, communications, and deterrence.",explain:"Cold War stability was never automatic. Leaders relied on deterrence and pressure while also needing communication and off-ramps from escalation."},
closing:"You escaped the bunker by recognizing that Cold War security depended on a dangerous balance: deterrence could restrain attack, but communication and diplomacy were essential when crises threatened to outrun control.",
takeaways:["Berlin showed alternatives to immediate armed confrontation.","The Cuban Missile Crisis combined pressure and negotiation.","Communication channels mattered during escalation.","Deterrence reduced some risks while creating others."],
sources:[{label:"U.S. State Department — Berlin Airlift",url:"https://history.state.gov/milestones/1945-1952/berlin-airlift"},{label:"U.S. State Department — Cuban Missile Crisis",url:"https://history.state.gov/milestones/1961-1968/cuban-missile-crisis"},{label:"National Archives — Cold War Records",url:"https://www.archives.gov/research/foreign-policy/cold-war"}]
};