window.ESCAPE_CONFIG={
title:"Escape the Castle",brief:"A medieval castle is more than a stone fortress. Its walls, gatehouse, chapel, hall, storage rooms, and documents reveal systems of defense, hierarchy, law, religion, and daily life.",
objectiveTitle:"Unlock the Keep",objective:"Move through four castle spaces, recover evidence about defense and society, then unlock the keep with a historically grounded final answer.",
stages:[
{type:"choice",title:"The Gatehouse",scene:"You face a narrow entrance protected by towers, heavy doors, and a portcullis.",clueTitle:"Clue: Defense by Design",clue:"Medieval castles used multiple defensive features—walls, towers, gatehouses, ditches, drawbridges, and narrow approaches—to slow attackers and expose them to defenders.",hint:"The strongest feature is not one object but a layered defensive system.",question:"Why was the gatehouse so important?",choices:["It concentrated several defenses at the most vulnerable entry point.","It was built mainly as a market stall.","It prevented defenders from seeing attackers.","It made walls unnecessary."],answer:0,wrong:"Think about where attackers had to enter.",danger:10,reward:{icon:"🛡️",item:"Gatehouse Key",note:"Evidence of layered castle defense."},explain:"The gatehouse combined obstacles, narrow space, elevation, and controlled access at a critical point."},
{type:"code",title:"The Charter Room",scene:"A document case contains a copy of Magna Carta.",clueTitle:"Clue: Magna Carta",clue:"Magna Carta was sealed in 1215 during conflict between King John and rebellious barons. It did not create modern democracy, but it placed written limits on royal action and became influential later.",hint:"Enter the year given in the clue.",question:"Enter the year Magna Carta was sealed.",answer:"1215",numeric:true,placeholder:"4-digit year",wrong:"The date appears in the document clue.",danger:10,reward:{icon:"📜",item:"Charter Fragment",note:"Evidence that medieval political power was negotiated and contested."},explain:"1215 is the key date. Magna Carta's later symbolic importance became far greater than its immediate medieval reach."},
{type:"sequence",title:"The Siege Stair",scene:"A siege record lists events during an attack on a fortified site.",clueTitle:"Clue: Siege Logic",clue:"Attackers often first isolated a castle, then bombarded or undermined defenses, attempted breaches or assaults, and finally forced surrender if defenders ran out of options.",hint:"Think from surrounding the castle to ending resistance.",question:"Tap the siege sequence in order.",items:["Isolate the castle","Damage or undermine defenses","Attempt a breach or assault","Force surrender or withdraw"],answer:[0,1,2,3],wrong:"Begin by cutting the defenders off before the breach attempt.",danger:12,reward:{icon:"🪜",item:"Siege Plan",note:"Shows how attacks targeted supplies, walls, and morale."},explain:"Sieges were often contests of time, engineering, supply, and morale rather than only dramatic wall assaults."},
{type:"choice",title:"The Great Hall",scene:"The hall contains evidence of feasting, administration, servants, retainers, and legal business.",clueTitle:"Clue: A Castle Is a Household",clue:"Castles were military sites, but also residences, administrative centers, courts, storage hubs, and symbols of lordship.",hint:"Avoid treating the castle as only a battlefield structure.",question:"What is the best interpretation of the great hall?",choices:["It shows that castles combined defense with household, political, and administrative functions.","It proves castles were used only during war.","It shows peasants lived as equals with lords inside the hall.","It had no role in governance or hospitality."],answer:0,wrong:"Use the range of activities listed in the clue.",danger:10,reward:{icon:"🏰",item:"Hall Seal",note:"Evidence of castle life beyond warfare."},explain:"The castle was a center of authority, residence, hospitality, storage, and justice as well as defense."}
],
finalLock:{icon:"🔐",question:"What is the strongest overall interpretation of a medieval castle?",choices:["A fortified center of defense, lordship, household life, administration, and political power.","Only a military bunker with no social role.","A building used mainly by merchants.","A structure with identical functions in every place and century."],answer:0,wrong:"Combine the gatehouse, charter, siege, and great-hall evidence.",explain:"Castles worked as both defensive structures and centers of social and political authority."},
closing:"You escaped the castle by reading architecture and documents together. Medieval power was built not only in stone, but through households, law, administration, warfare, and negotiated authority.",
takeaways:["Gatehouses concentrated defensive systems.","Sieges depended on supply and engineering.","Magna Carta reflects contested royal authority.","Castles were homes and administrative centers as well as fortresses."],
sources:[{label:"British Library — Magna Carta",url:"https://www.bl.uk/magna-carta"},{label:"English Heritage — Castles",url:"https://www.english-heritage.org.uk/learn/story-of-england/medieval/castles/"}]
};