const CFG=window.TIME_RUSH_CONFIG;
const ROUNDS=CFG.rounds;
let roundIndex=0,placed=[],phase="intro",timer=null,timeLeft=0,score=0,attempts=0,perfect=false,audioCtx=null;
const $=s=>document.querySelector(s);
const E={main:$("#mainPanel"),action:$("#primaryAction"),secondary:$("#secondaryAction"),time:$("#timeValue"),round:$("#roundValue"),score:$("#scoreValue"),hint:$("#hintBox"),result:$("#resultBox"),slots:$("#timelineSlots"),progress:$("#progressBar"),completion:$("#completion"),badgeRank:$("#badgeRank"),badgeScore:$("#badgeScore")};
const TONES=["tone-maroon","tone-blue","tone-green","tone-gold"];
function audioReady(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function tone(freq,dur=.08,type="sine",vol=.14,delay=0){audioReady();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,audioCtx.currentTime+delay);g.gain.linearRampToValueAtTime(vol,audioCtx.currentTime+delay+.01);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+delay+dur);o.connect(g);g.connect(audioCtx.destination);o.start(audioCtx.currentTime+delay);o.stop(audioCtx.currentTime+delay+dur+.03)}
function sfx(n){if(n==="place"){tone(500,.08);tone(760,.1,"sine",.12,.05)}if(n==="wrong"){tone(200,.18,"sawtooth");tone(145,.22,"sawtooth",.12,.12)}if(n==="timeout"){tone(170,.15,"square");tone(120,.22,"square",.12,.18)}if(n==="unlock"){[523,659,784,1046].forEach((f,i)=>tone(f,.16,"sine",.18,i*.08))}if(n==="win"){[392,523,659,784,1046].forEach((f,i)=>tone(f,.22,"sine",.18,i*.1))}}
document.addEventListener("pointerdown",audioReady,{once:true});
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function fmt(n){return"0:"+String(Math.max(0,n)).padStart(2,"0")}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function runTimer(seconds,done){stopTimer();timeLeft=seconds;E.time.textContent=fmt(timeLeft);timer=setInterval(()=>{timeLeft--;E.time.textContent=fmt(timeLeft);if(phase==="arrange"&&timeLeft===Math.floor(seconds/2)){E.hint.hidden=false;E.hint.innerHTML="<strong>Hint:</strong> "+ROUNDS[roundIndex].hint}if(timeLeft<=0){stopTimer();done()}},1000)}
function renderProgress(){E.progress.innerHTML=ROUNDS.map((_,i)=>'<div class="progress-dot '+(i<roundIndex?"done":i===roundIndex?"current":"")+'">'+(i+1)+'</div>').join("");E.round.textContent=(roundIndex+1)+"/"+ROUNDS.length}
function renderTimeline(){const r=ROUNDS[roundIndex],count=r.events.length;E.slots.style.setProperty("--slot-count",count);E.slots.innerHTML=Array.from({length:count},(_,i)=>{const ev=r.events.find(x=>x.id===placed[i]);return'<button class="timeline-slot '+(ev?"filled":"empty")+'" data-index="'+i+'" '+(ev?'title="Tap to remove"':'disabled')+'><span class="timeline-label">'+(ev?ev.label:"")+'</span></button>'}).join("");E.slots.querySelectorAll(".filled").forEach(b=>b.onclick=()=>{placed.splice(Number(b.dataset.index),1);renderCards();renderTimeline();sync()})}
function renderCards(){const r=ROUNDS[roundIndex],order=window._order||r.events;E.main.innerHTML='<h2>Arrange the Timeline</h2><p class="board-note">Tap the events in the order you believe they happened. They will light up on the timeline above. Tap a timeline event to remove it and try again.</p><div class="card-grid" id="cardGrid"></div>';$("#cardGrid").innerHTML=order.map((ev,i)=>'<button class="event-card '+TONES[i%4]+' '+(placed.includes(ev.id)?"placed":"")+'" data-id="'+ev.id+'"><strong>'+ev.label+'</strong><small>'+ev.detail+'</small></button>').join("");document.querySelectorAll(".event-card:not(.placed)").forEach(b=>b.onclick=()=>{if(placed.length>=r.events.length)return;sfx("place");placed.push(b.dataset.id);renderCards();renderTimeline();sync()})}
function sync(){E.action.disabled=placed.length!==ROUNDS[roundIndex].events.length}
function setTone(i){E.action.classList.remove(...TONES);E.action.classList.add(TONES[i%4])}
function showIntro(){phase="intro";renderProgress();renderTimeline();E.time.textContent="—";E.score.textContent=score;E.hint.hidden=true;E.result.hidden=true;E.secondary.hidden=true;E.main.innerHTML='<h2>'+CFG.title+': Time Rush</h2><div class="study-card"><h3>How to Play</h3><p>Study each short history reading before it disappears. Then arrange the events in chronological order. You need 100% accuracy to unlock the next level. If the order is wrong or time expires, study the correct sequence and retry. Master all nine levels to earn the '+CFG.title+' badge.</p></div>';E.action.textContent="Start Game";E.action.disabled=false;setTone(0)}
function study(){phase="study";placed=[];perfect=false;attempts++;window._order=null;renderProgress();renderTimeline();const r=ROUNDS[roundIndex];E.hint.hidden=true;E.result.hidden=true;E.secondary.hidden=true;E.main.innerHTML='<h2>Study the Past</h2><div class="study-card"><div class="study-timer">Study Time · '+r.studySeconds+' seconds</div><h3>'+r.title+'</h3><p>'+r.study+'</p></div>';E.action.textContent="I'm Ready";E.action.disabled=false;setTone(1);runTimer(r.studySeconds,arrange)}
function arrange(){stopTimer();phase="arrange";const r=ROUNDS[roundIndex];window._order=shuffle(r.events);placed=[];renderCards();renderTimeline();E.hint.hidden=true;E.result.hidden=true;E.secondary.hidden=false;E.secondary.textContent="Clear Timeline";E.secondary.onclick=()=>{placed=[];renderCards();renderTimeline();sync()};E.action.textContent="Submit Timeline";E.action.disabled=true;setTone(2);runTimer(r.playSeconds,()=>submit(true))}
function celebrate(finalLevel){const old=document.querySelector(".level-win-flash");if(old)old.remove();const f=document.createElement("div");f.className="level-win-flash";f.innerHTML='<div class="level-win-inner"><div class="level-win-kicker">'+(finalLevel?CFG.masteredLabel:"TIMELINE LOCKED IN")+'</div><div class="level-win-title">YOU DID IT!</div><div class="level-win-next">'+(finalLevel?"Badge earned.":"Level "+(roundIndex+2)+" unlocked.")+'</div></div>';document.body.appendChild(f);requestAnimationFrame(()=>f.classList.add("show"));setTimeout(()=>f.classList.remove("show"),1450);setTimeout(()=>f.remove(),1900)}
function submit(auto=false){if(phase!=="arrange")return;stopTimer();phase="feedback";const r=ROUNDS[roundIndex],correct=r.events.map(e=>e.id);let hits=0;correct.forEach((id,i)=>{if(placed[i]===id)hits++});perfect=hits===r.events.length;const pct=Math.round(hits/r.events.length*100);E.result.hidden=false;E.hint.hidden=true;E.secondary.hidden=true;placed=[...correct];renderTimeline();if(!perfect){auto?sfx("timeout"):sfx("wrong");E.result.innerHTML='<strong>'+(auto?"⏳ TIME’S UP — LEVEL NOT CLEARED":"NOT YET — TRY THIS LEVEL AGAIN")+'</strong><br><b>Correct:</b> '+hits+' &nbsp; <b>Wrong:</b> '+(r.events.length-hits)+' &nbsp; <b>Accuracy:</b> '+pct+'%<br><span class="mastery-note">You need 100% to unlock the next level. Study the correct order above, then take another run.</span><ol class="feedback-order">'+r.events.map(e=>'<li>'+e.label+'</li>').join("")+'</ol>';E.action.disabled=false;E.action.textContent="Retry Level "+(roundIndex+1);setTone(0);return}score+=100;E.score.textContent=score;sfx("unlock");celebrate(roundIndex===ROUNDS.length-1);E.result.innerHTML='<strong>🏆 PERFECT — LEVEL '+(roundIndex+1)+' CLEARED!</strong><br><b>Accuracy:</b> 100% &nbsp; <b>Attempts:</b> '+attempts+'<br><span class="mastery-note">'+(roundIndex===ROUNDS.length-1?"Every "+CFG.title+" timeline is mastered. Claim your badge.":"Level "+(roundIndex+2)+" is now unlocked.")+'</span>';E.action.disabled=false;E.action.textContent=roundIndex===ROUNDS.length-1?"Claim "+CFG.title+" Badge":"Enter Level "+(roundIndex+2);setTone(3)}
function advance(){if(!perfect)return;if(roundIndex===ROUNDS.length-1){finish();return}roundIndex++;attempts=0;study()}
function finish(){stopTimer();phase="complete";sfx("win");localStorage.setItem(CFG.storageKey+"_complete","1");localStorage.setItem(CFG.storageKey+"_score","100");E.badgeRank.textContent=CFG.rank;E.badgeScore.textContent="100% mastery · "+(ROUNDS.length*100)+" points";E.completion.classList.add("show")}
E.action.onclick=()=>{audioReady();if(phase==="intro")study();else if(phase==="study")arrange();else if(phase==="arrange")submit(false);else if(phase==="feedback"){if(perfect)advance();else study()}};
$("#playAgain").onclick=()=>location.reload();$("#vaultReturn").onclick=()=>location.href="/examine-the-past-home/games/";showIntro();