window.MAP_QUEST_CONFIG={
title:"Trade Routes Quest",brief:"Trade routes carried far more than goods. They moved technologies, religions, diseases, languages, financial practices, and political influence.",
question:"Use route clues to identify the exchange network being described.",
rounds:[
{title:"Across Eurasia",prompt:"Find the network connecting East Asia, Central Asia, the Middle East, and Europe through linked overland routes.",clueTitle:"Clue: Caravans and Oasis Cities",clue:"Merchants rarely traveled the entire distance. Goods moved through many intermediaries across deserts, steppes, mountain passes, and oasis cities.",places:[{name:"Silk Roads",detail:"Eurasian overland networks"},{name:"Trans-Saharan routes",detail:"North and West Africa"},{name:"Indian Ocean routes",detail:"Maritime Asia and Africa"},{name:"Atlantic system",detail:"Atlantic basin"}],answer:0,explain:"The Silk Roads were a web of interconnected Eurasian routes rather than one single road."},
{title:"Across the Sahara",prompt:"Choose the network that linked North Africa with West African states and markets.",clueTitle:"Clue: Camel Caravans",clue:"Caravans crossed desert routes carrying goods such as salt southward and gold northward, linking cities across the Sahel and Maghreb.",places:[{name:"Trans-Saharan routes",detail:"Sahara / Sahel"},{name:"Silk Roads",detail:"Central Eurasia"},{name:"Baltic trade",detail:"Northern Europe"},{name:"Pacific trade",detail:"Pacific basin"}],answer:0,explain:"Trans-Saharan routes connected West African states to North African and Mediterranean commercial systems."},
{title:"Monsoon Sea",prompt:"Identify the maritime system that relied on predictable seasonal winds.",clueTitle:"Clue: Sail With the Monsoon",clue:"Merchants timed voyages across waters linking East Africa, Arabia, South Asia, and Southeast Asia to seasonal wind patterns.",places:[{name:"Indian Ocean trade",detail:"East Africa to Southeast Asia"},{name:"Mediterranean cabotage",detail:"Mediterranean coast"},{name:"Trans-Saharan trade",detail:"Desert caravans"},{name:"Silk Roads",detail:"Overland Eurasia"}],answer:0,explain:"Indian Ocean merchants used monsoon wind cycles to plan long-distance voyages."},
{title:"Atlantic Forced Migration",prompt:"Identify the route system that forcibly carried millions of Africans across the Atlantic.",clueTitle:"Clue: Middle Passage",clue:"European colonial economies created a transatlantic system in which enslaved Africans were violently transported to the Americas under horrific conditions.",places:[{name:"Transatlantic slave trade",detail:"Africa to the Americas"},{name:"Silk Roads",detail:"Eurasia"},{name:"Indian Ocean monsoon trade",detail:"Africa and Asia"},{name:"Hanseatic trade",detail:"Northern Europe"}],answer:0,explain:"The Middle Passage was the forced Atlantic crossing endured by enslaved Africans within the transatlantic slave trade."}
],
challenge:{question:"Why are trade routes important to historians?",choices:["They show only where luxury goods traveled.","They reveal networks through which goods, people, ideas, technologies, disease, and power moved.","They matter only after 1800.","Every route was controlled by one empire."],answer:1,explain:"Exchange networks connect economic history to cultural, political, technological, and demographic change."},
closing:"A route is not just a line on a map. It is a moving network of people, environments, risks, institutions, and ideas.",
takeaways:["Most trade networks were multi-stage systems.","Seasonal winds could structure maritime exchange.","Caravan routes depended on water, animals, and stopping points.","Forced migration must be distinguished from voluntary trade and travel."]
};