window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Writers",brief:"Identify writers from their works, genres, ideas, audiences, and the historical worlds they helped describe or challenge.",question:"Can you identify the writer before all three clues are revealed?",
people:[
{name:"William Shakespeare",roundTitle:"Identity 1 · English Stage",clues:["I wrote for the London stage around the turn of the 17th century.","My works include tragedies, comedies, and histories.","Hamlet, Macbeth, and Romeo and Juliet are among my most famous plays."],options:["Christopher Marlowe","William Shakespeare","Ben Jonson","Geoffrey Chaucer"],answer:1,explain:"Shakespeare's plays became some of the most influential works in English-language literature."},
{name:"Mary Wollstonecraft",roundTitle:"Identity 2 · Rights and Education",clues:["I was an English writer of the late 18th century.","I argued that women were rational beings deserving serious education.","My best-known work is A Vindication of the Rights of Woman."],options:["Jane Austen","Mary Wollstonecraft","Mary Shelley","Aphra Behn"],answer:1,explain:"Wollstonecraft's writing became foundational to later debates about women's education and equality."},
{name:"Frederick Douglass",roundTitle:"Identity 3 · Autobiography as Evidence",clues:["I was born enslaved and later became an abolitionist.","My life story challenged proslavery claims by documenting slavery from firsthand experience.","My 1845 Narrative became internationally influential."],options:["Frederick Douglass","Olaudah Equiano","Harriet Jacobs","Solomon Northup"],answer:0,explain:"Douglass used autobiography as both personal testimony and a powerful abolitionist argument."},
{name:"Chinua Achebe",roundTitle:"Identity 4 · Colonial Encounter",clues:["I was a Nigerian novelist.","My fiction challenged European portrayals of Africa.","Things Fall Apart, published in 1958, depicts Igbo society and colonial disruption."],options:["Wole Soyinka","Chinua Achebe","Ngũgĩ wa Thiong'o","James Baldwin"],answer:1,explain:"Achebe's work helped reshape global literature by centering African perspectives on colonialism and cultural change."},
{name:"George Orwell",roundTitle:"Identity 5 · Power and Language",clues:["My real name was Eric Blair.","I wrote political fiction and essays in the 20th century.","Animal Farm and Nineteen Eighty-Four are among my best-known works."],options:["George Orwell","Aldous Huxley","H. G. Wells","Arthur Koestler"],answer:0,explain:"Orwell's writing explored propaganda, authoritarianism, class, language, and political power."}
],
closing:"Writers are historical witnesses as well as artists. Their works can reveal assumptions, conflicts, hopes, and power structures in the societies that produced them.",
takeaways:["Literature can function as historical evidence.","Genre affects how writers communicate ideas.","Autobiography can challenge dominant narratives.","Writers often shape later political and cultural debates."]
};