window.CASE_FILE_CONFIG={
title:"The Lincoln File",caseNumber:"02",location:"Washington, D.C. · April 1865",
brief:"On April 14, 1865, President Abraham Lincoln was shot at Ford's Theatre by actor John Wilkes Booth. Booth escaped, Secretary of State William Seward was attacked the same night, and investigators uncovered a network that had previously planned to kidnap Lincoln.",
question:"What does the evidence reveal about the planning behind Lincoln's assassination?",
assignment:"Your job is not to guess motives. Separate documented planning, assigned roles, escape evidence, and later interpretation.",
midCaseTwist:{icon:"🎭",title:"The Plot Was Older Than the Murder",text:"Evidence shows that Booth's group had been planning to kidnap Lincoln before the plan changed to assassination. That means the final attack may have been both sudden in timing and rooted in a longer conspiracy."},
crossExam:{question:"Which conclusion best fits the evidence about the April 14 plot?",choices:["Booth acted entirely alone and no one else had assigned roles.","A preexisting kidnapping conspiracy evolved into a coordinated assassination plan involving multiple targets.","The Confederate government is definitively proven to have directly ordered the assassination.","Everyone who knew Booth knew about the murder plan."],answer:1,explain:"The documented record strongly supports a Booth-led conspiracy that evolved from kidnapping into assassination. Broader claims require evidence beyond association or sympathy."},
closingCaution:"The evidence strongly supports a coordinated Booth conspiracy. Historians still distinguish that documented conspiracy from broader claims about people whose knowledge or responsibility remains disputed.",
evidence:[
{id:"e1",num:"Evidence 01",title:"Ford's Theatre Crime Scene",date:"Primary event · April 14, 1865",sourceType:"Crime Scene",text:"At about 10:15 p.m., John Wilkes Booth entered the presidential box at Ford's Theatre, shot Lincoln with a single-shot derringer, stabbed Major Henry Rathbone during his escape, and fled through the rear of the theatre.",observation:"The attack was deliberate, timed during a public performance, and followed by a prepared escape route.",question:"What does this evidence establish most directly?",choices:["Booth intentionally attacked Lincoln and escaped the theatre.","Booth had no prior knowledge Lincoln would attend.","The entire conspiracy is explained by this evidence alone.","No one else was involved in any related plan."],answer:0,explain:"The theatre evidence establishes Booth's direct action. It does not, by itself, establish the full size of the conspiracy."},
{id:"e2",num:"Evidence 02",title:"The Earlier Kidnapping Plot",date:"Planning evidence · 1864–March 1865",sourceType:"Conspiracy Record",text:"National Park Service records describe Booth assembling a group in 1864 to kidnap Lincoln and take him south. A planned abduction attempt in March 1865 failed.",observation:"Booth had already organized accomplices and roles months before the assassination.",question:"Why is the kidnapping plot important?",choices:["It shows the assassination emerged from an existing conspiracy network.","It proves no murder was ever planned.","It shows Booth had no accomplices.","It proves every Confederate sympathizer joined the plot."],answer:0,explain:"The kidnapping scheme demonstrates prior organization. The later murder plot did not begin from zero."},
{id:"e3",num:"Evidence 03",title:"Multiple Targets",date:"Coordinated attacks · April 14, 1865",sourceType:"Conspirator Record",text:"Booth assigned Lewis Powell to kill Secretary of State William Seward and George Atzerodt to kill Vice President Andrew Johnson. Powell attacked Seward and members of his household. Atzerodt did not carry out his assigned attack.",observation:"The plan reached beyond Lincoln and aimed at several senior government leaders on the same night.",question:"What does the multiple-target plan most strongly indicate?",choices:["A coordinated attempt to strike several leaders at once.","A random series of unrelated crimes.","Proof that every target was killed.","Proof that the attack had no political purpose."],answer:0,explain:"Separate assigned targets are strong evidence of coordinated planning, even though not every assignment was completed."},
{id:"e4",num:"Evidence 04",title:"Booth's Own Journal",date:"Primary source · April 1865",sourceType:"Primary Source",text:"While fleeing, Booth wrote that his group had spent months working on a plan to capture Lincoln before deciding that something more decisive had to be done as the Confederacy collapsed.",observation:"Booth's own writing links the assassination to the earlier kidnapping conspiracy.",question:"How should an investigator use Booth's journal?",choices:["As direct evidence of Booth's thinking, while recognizing that he was defending his own actions.","As neutral proof of every conspirator's thoughts.","As evidence written years later by someone uninvolved.","As proof that no kidnapping plot existed."],answer:0,explain:"A perpetrator's journal is valuable primary evidence, but it is also self-justifying and must be compared with other records."},
{id:"e5",num:"Evidence 05",title:"Escape With David Herold",date:"Escape route · April 14–26, 1865",sourceType:"Movement Evidence",text:"After the attacks, David Herold met Booth in Maryland and remained with him during much of the twelve-day escape through Maryland and Virginia. Herold had also guided Powell to Seward's home earlier that night.",observation:"The escape route connects Booth to another participant who had a defined role in the same plot.",question:"What does Herold's role show?",choices:["The assassination and escape involved coordinated assistance.","Booth never met any conspirator after the shooting.","Herold was an uninvolved stranger.","The escape proves a foreign government directed the plot."],answer:0,explain:"Herold's movements connect the Seward attack, Booth's escape, and the wider conspiracy without proving every broader theory."},
{id:"e6",num:"Evidence 06",title:"Meeting Places and Supplies",date:"Network evidence · 1865",sourceType:"Location Evidence",text:"NPS records identify Mary Surratt's Washington boarding house and Maryland tavern as places used by Booth and members of his network. Booth and Herold stopped at the tavern for supplies after the assassination. Historians continue to debate the extent of Mary Surratt's knowledge and responsibility.",observation:"The conspiracy had recurring meeting points and logistical support, but individual knowledge within the network was not identical.",question:"What is the strongest conclusion from this file?",choices:["The plot used a network of people and places, but responsibility must be judged person by person.","Everyone connected to the locations knew every detail.","The tavern proves a foreign government ordered the assassination.","Meeting at a boarding house proves nothing at all."],answer:0,explain:"Networks can support a conspiracy without every person in the network having the same knowledge or intent."}
],
theories:[
{id:"evolved",title:"Kidnapping Plot Evolved Into Assassination",desc:"Booth's existing conspiracy shifted from kidnapping to coordinated murder as the war ended.",strong:["e2","e3","e4","e5","e6"],weak:["e1"],summary:"This explanation fits the long-running kidnapping plan, assigned assassination targets, Booth's own journal, and the coordinated escape network. It is strongly supported by the surviving record."},
{id:"lone",title:"Booth Acted Alone",desc:"Booth alone planned and carried out the assassination, while others became involved only afterward.",strong:["e1"],weak:["e2","e3","e4","e5","e6"],summary:"Booth personally shot Lincoln, but the evidence of assigned targets, earlier planning, and coordinated assistance makes a fully lone-actor explanation difficult to sustain."},
{id:"government",title:"A Larger Confederate Government Order",desc:"The assassination was directly ordered by senior Confederate officials.",strong:[],weak:["e2","e3","e4","e5","e6"],summary:"Booth and several conspirators had Confederate sympathies and contacts, but association is not the same as direct proof that senior Confederate leaders ordered the April 14 assassination."},
{id:"improvised",title:"An Improvised Murder Using an Existing Network",desc:"Booth made the final decision quickly but used a network created during the earlier kidnapping plan.",strong:["e1","e2","e3","e4","e5"],weak:["e6"],summary:"The final timing may have been compressed, but the network, assigned roles, and earlier kidnapping plan show that the attack relied on existing organization."}
],
sources:[
{label:"NPS — FAQ: The Assassination",url:"https://home.nps.gov/foth/learn/historyculture/faq-the-assassination.htm"},
{label:"NPS — The Lincoln Conspirators",url:"https://home.nps.gov/foth/learn/historyculture/the-lincoln-conspirators.htm"},
{label:"NPS — The Assassin's Escape",url:"https://home.nps.gov/foth/learn/historyculture/the-assassin-s-escape.htm"},
{label:"NPS — Booth's Journal",url:"https://home.nps.gov/foth/learn/historyculture/thoughts-from-an-assassin-the-journal-of-john-wilkes-booth.htm"}
]};