window.CONNECTIONS_CONFIG={
title:"Cause & Effect: Revolutions",brief:"Revolutions emerge from chains: grievances create pressure, events become triggers, political authority responds, and consequences spread far beyond the first uprising.",question:"Can you connect revolutionary causes, triggers, turning points, and consequences without confusing one for another?",
rounds:[
{title:"American Revolution",prompt:"Connect each condition or event to its historical effect.",left:[{id:"tax",label:"Imperial taxation after the Seven Years' War",detail:"British North America"},{id:"lex",label:"Lexington and Concord",detail:"April 1775"},{id:"decl",label:"Declaration of Independence",detail:"July 1776"},{id:"york",label:"Yorktown",detail:"1781"}],right:[{id:"war",label:"Open war begins",detail:"Armed conflict"},{id:"ind",label:"Colonies formally claim independence",detail:"Political break"},{id:"resent",label:"Colonial resistance intensifies",detail:"Political grievance"},{id:"britdef",label:"Major British defeat helps move war toward peace",detail:"Military turning point"}],links:{tax:{right:"resent",explain:"Taxes and imperial reforms intensified disputes over representation and authority."},lex:{right:"war",explain:"The fighting at Lexington and Concord marked the start of open armed conflict."},decl:{right:"ind",explain:"The Declaration transformed resistance into a formal claim of independent statehood."},york:{right:"britdef",explain:"Cornwallis's surrender at Yorktown was a decisive blow to Britain's war effort."}}},
{title:"French Revolution",prompt:"Link pressures and turning points to their consequences.",left:[{id:"debt",label:"Fiscal crisis + unequal tax system",detail:"1780s France"},{id:"bastille",label:"Storming of the Bastille",detail:"July 1789"},{id:"republic",label:"Monarchy abolished",detail:"1792"},{id:"terror",label:"Reign of Terror",detail:"1793–1794"}],right:[{id:"radical",label:"Revolution becomes more radical",detail:"Political escalation"},{id:"symbol",label:"Popular uprising becomes a revolutionary symbol",detail:"Mass action"},{id:"estates",label:"Pressure for political reform intensifies",detail:"Crisis of monarchy"},{id:"exec",label:"Republic replaces monarchy",detail:"New political order"}],links:{debt:{right:"estates",explain:"Financial crisis forced the monarchy to seek new political solutions and helped trigger broader demands."},bastille:{right:"symbol",explain:"The Bastille's fall became a powerful symbol of popular revolutionary action."},republic:{right:"exec",explain:"A republic replaced the monarchy and Louis XVI was later executed."},terror:{right:"radical",explain:"The Terror reflected intense radicalization, war, and internal political conflict."}}},
{title:"Haitian Revolution",prompt:"Connect revolutionary developments to the transformations they produced.",left:[{id:"enslaved",label:"Mass uprising of enslaved people",detail:"1791"},{id:"abolition",label:"French abolition of slavery",detail:"1794"},{id:"napoleon",label:"Napoleon sends expedition",detail:"1802"},{id:"independence",label:"Haitian independence",detail:"1804"}],right:[{id:"state",label:"Independent Black republic emerges",detail:"New nation"},{id:"war2",label:"Revolutionary war expands",detail:"Colonial order challenged"},{id:"restore",label:"Fear of restoring slavery intensifies resistance",detail:"Renewed conflict"},{id:"legal",label:"Slavery legally abolished in French colonies",detail:"Policy change"}],links:{enslaved:{right:"war2",explain:"The 1791 uprising transformed Saint-Domingue into a major revolutionary war."},abolition:{right:"legal",explain:"French authorities abolished slavery during the revolutionary crisis."},napoleon:{right:"restore",explain:"The French expedition and restoration of slavery elsewhere sharpened fears of re-enslavement."},independence:{right:"state",explain:"Haiti declared independence in 1804 after defeating French forces."}}},
{title:"Russian Revolution",prompt:"Connect crisis, revolution, and civil conflict.",left:[{id:"warww1",label:"World War I pressures",detail:"Food, military, political crisis"},{id:"feb",label:"February Revolution",detail:"1917"},{id:"oct",label:"Bolshevik seizure of power",detail:"October 1917"},{id:"civil",label:"Russian Civil War",detail:"1918–1921"}],right:[{id:"bol",label:"Bolsheviks form a new government",detail:"Power shift"},{id:"abdicate",label:"Tsar Nicholas II abdicates",detail:"End of monarchy"},{id:"soviet",label:"Bolshevik victory consolidates new regime",detail:"Postwar outcome"},{id:"collapse",label:"Existing political order loses legitimacy",detail:"Wartime destabilization"}],links:{warww1:{right:"collapse",explain:"Military losses, shortages, and political failures weakened the tsarist system."},feb:{right:"abdicate",explain:"Mass unrest and political breakdown led Nicholas II to abdicate."},oct:{right:"bol",explain:"The Bolsheviks overthrew the Provisional Government and took power."},civil:{right:"soviet",explain:"Bolshevik victory in the civil war consolidated the new revolutionary state."}}}
],
challenge:{question:"Which pattern appears across many revolutions?",choices:["A single grievance automatically causes immediate revolution.","Long-term pressures interact with triggering events, political choices, organized groups, and unpredictable turning points.","Revolutions always produce stable democracy immediately.","Foreign wars never affect domestic revolutions."],answer:1,explain:"Revolutions are chains, not single causes. Structural pressures matter, but so do triggers, organizations, war, leadership, and contingency."},
closing:"Revolutions are historical systems of cause and effect. The same event can be a consequence of one crisis and the cause of the next.",
takeaways:["Separate long-term causes from immediate triggers.","Turning points change what actors believe is possible.","War often accelerates revolutionary crisis.","Revolutionary outcomes frequently differ from original goals."]
};