window.CASE_FILE_CONFIG={
title:"The Cold War Brief",caseNumber:"04",location:"Cuba · Washington · Moscow · October 1962",
brief:"In October 1962, U.S. reconnaissance photographs revealed Soviet nuclear missile sites in Cuba. For thirteen days, the United States and Soviet Union moved through military alerts, a naval quarantine, secret diplomacy, and intense uncertainty.",
question:"Why did the Cuban Missile Crisis end without nuclear war?",
assignment:"Treat this like an intelligence brief. Compare military pressure, communication, compromise, and contingency. Do not reduce the outcome to a single dramatic moment.",
midCaseTwist:{icon:"☢️",title:"October 27: The Crisis Gets Worse",text:"A U-2 aircraft was shot down over Cuba while diplomatic messages were becoming more complicated. The same day, Kennedy's team prepared for the possibility of an attack while still searching for a diplomatic exit."},
crossExam:{question:"Which explanation best fits the settlement that ended the crisis?",choices:["One side simply surrendered with no reciprocal assurances.","Controlled pressure and diplomacy produced a deal: Soviet missiles were removed, the U.S. publicly pledged not to invade Cuba, and the Turkey missile issue was handled quietly.","The United Nations independently ordered both sides to end the crisis.","The crisis ended before any negotiations occurred."],answer:1,explain:"The public settlement and the private handling of the Jupiter missiles show that coercion and compromise operated together."},
closingCaution:"The crisis was resolved, but the documentary record also shows danger, misperception, military pressure, and contingency. Avoid turning a near-catastrophe into a simple story of flawless control.",
evidence:[
{id:"e1",num:"Evidence 01",title:"The U-2 Photographs",date:"Reconnaissance · October 14–16, 1962",sourceType:"Intelligence",text:"U.S. U-2 photographs provided evidence that the Soviet Union was constructing nuclear missile sites in Cuba. The photographs became the foundation for Kennedy's response.",observation:"The crisis began with intelligence that changed what U.S. leaders believed was happening in Cuba.",question:"What does this evidence establish?",choices:["The United States had photographic evidence of Soviet missile sites in Cuba.","The crisis began because of a newspaper rumor.","The Soviet Union had no weapons in Cuba.","No one in Washington saw the photographs."],answer:0,explain:"Intelligence evidence transformed suspicion into a documented strategic crisis."},
{id:"e2",num:"Evidence 02",title:"Quarantine Instead of Immediate Attack",date:"U.S. decision · October 1962",sourceType:"Decision Record",text:"Kennedy and his advisers considered military options but chose a naval quarantine while demanding removal of the missiles.",observation:"The response applied pressure while leaving more time for communication than an immediate air strike or invasion would have.",question:"Why did the quarantine matter?",choices:["It created pressure without immediately beginning a full attack.","It guaranteed there was no risk of war.","It removed all Soviet missiles instantly.","It ended the crisis before diplomacy began."],answer:0,explain:"The quarantine was coercive, but it also preserved decision time and space for negotiation."},
{id:"e3",num:"Evidence 03",title:"Letters Between Leaders",date:"Diplomacy · October 24–27, 1962",sourceType:"Primary Documents",text:"Kennedy and Khrushchev exchanged messages arguing over security, Cuba, the quarantine, and missiles near each other's territory. The correspondence revealed both confrontation and an effort to find terms for de-escalation.",observation:"Direct communication kept a diplomatic channel open while military forces remained on alert.",question:"What role did the letters play?",choices:["They created a channel for signaling demands, fears, and possible compromise.","They had no connection to the crisis.","They proved both leaders agreed from the start.","They immediately removed every military risk."],answer:0,explain:"Communication did not eliminate danger, but it made negotiation possible during escalation."},
{id:"e4",num:"Evidence 04",title:"A U-2 Is Shot Down",date:"Escalation · October 27, 1962",sourceType:"Military Event",text:"A U.S. U-2 reconnaissance aircraft was shot down over Cuba on October 27. U.S. leaders continued to prepare military options while also pursuing a diplomatic resolution.",observation:"The crisis could worsen even while leaders were trying to control it.",question:"What does this incident demonstrate?",choices:["Events on the ground could escalate faster than diplomacy could control them.","The crisis was already over by October 27.","Military forces had no role in the crisis.","Both sides had complete control over every action."],answer:0,explain:"The shootdown is a reminder that crisis management operated under uncertainty and imperfect control."},
{id:"e5",num:"Evidence 05",title:"The Public Settlement",date:"Resolution · October 28, 1962",sourceType:"Diplomatic Outcome",text:"The Soviet Union agreed to dismantle and remove the missiles from Cuba. The United States publicly pledged not to invade Cuba if the missile threat was removed.",observation:"The final public arrangement included commitments by both sides.",question:"What does the public settlement show?",choices:["The resolution involved reciprocal commitments, not only unilateral retreat.","Only the United States made a commitment.","Only the Soviet Union made a commitment.","No agreement was reached."],answer:0,explain:"The public deal reduced the immediate security concerns of both governments."},
{id:"e6",num:"Evidence 06",title:"The Turkey Missile Context",date:"Backchannel and aftermath · 1962–1963",sourceType:"Declassified Record",text:"Khrushchev raised U.S. Jupiter missiles in Turkey during the crisis. U.S. records show that officials privately indicated those missiles were already expected to be removed, and the Jupiters were withdrawn from Turkey in 1963.",observation:"The public story was simpler than the private diplomacy surrounding the settlement.",question:"How should this evidence affect the case?",choices:["It shows that private compromise and broader strategic concerns were part of the resolution.","It proves the public settlement never happened.","It shows Turkey had no connection to Cold War strategy.","It proves the crisis was staged."],answer:0,explain:"Declassified documents reveal a more complicated settlement than a simple public victory narrative."}
],
theories:[
{id:"pressure-diplomacy",title:"Controlled Pressure + Diplomatic Compromise",desc:"Military pressure created leverage while communication and reciprocal assurances created an exit.",strong:["e1","e2","e3","e5","e6"],weak:["e4"],summary:"This theory fits the intelligence trigger, quarantine, leader-to-leader communication, reciprocal public commitments, and the quieter Turkey missile context."},
{id:"force-only",title:"Military Force Alone Ended the Crisis",desc:"The Soviet Union backed down only because U.S. military superiority left no other option.",strong:["e2"],weak:["e3","e5","e6"],summary:"Military pressure mattered, but the documentary record also shows negotiation, assurances, and compromise."},
{id:"diplomacy-only",title:"Diplomacy Alone Ended the Crisis",desc:"Communication solved the crisis independently of military pressure.",strong:["e3","e5","e6"],weak:["e1","e2","e4"],summary:"Diplomacy was crucial, but it unfolded while military forces were deployed and escalation remained possible."},
{id:"luck",title:"The Outcome Was Mostly Luck",desc:"The crisis ended successfully mainly because dangerous events happened not to trigger war.",strong:["e4"],weak:["e2","e3","e5","e6"],summary:"Contingency and luck mattered, but the record also shows deliberate choices designed to slow escalation and create an exit."}
],
sources:[
{label:"National Archives — Cuban Missile Crisis",url:"https://www.archives.gov/news/topics/cuban-missile-crisis"},
{label:"U.S. State Department Historian — Cuban Missile Crisis",url:"https://history.state.gov/milestones/1961-1968/cuban-missile-crisis"},
{label:"JFK Library — Khrushchev Letter, Oct. 27",url:"https://microsites.jfklibrary.org/cmc/oct27/doc4.html"},
{label:"National Archives — Berlin/Cuban Cold War Records",url:"https://www.archives.gov/research/foreign-policy/cold-war"}
]};