window.CASE_FILE_CONFIG={
title:"The Missing Colony",
caseNumber:"01",
location:"Roanoke Island, 1590",
brief:"In 1587, 117 English colonists were left at Roanoke Island. Governor John White sailed to England for supplies. War with Spain delayed his return for three years. When he finally came back in 1590, the settlement was empty.",
question:"What happened to the Roanoke colonists?",
evidence:[
{id:"e1",num:"Evidence 01",title:"The Carved Message",date:"Primary account · August 1590",sourceType:"Primary Account",text:"John White recorded finding “CRO” carved into a tree and “CROATOAN” carved into a post at the abandoned settlement. Before leaving in 1587, White had arranged a signal: if the colonists moved under distress, they were to carve a cross above their destination message. White did not report that distress mark.",observation:"A named destination was deliberately left behind, and the agreed distress symbol was absent.",question:"What conclusion is best supported by this clue?",choices:["The colonists probably tried to communicate where they had gone.","The settlement was certainly destroyed by a hurricane.","The Spanish definitely captured the colonists.","The colonists left no useful information."],answer:0,explain:"The carving is direct evidence that the colonists wanted a later search party to notice the name Croatoan. It does not prove what happened after they left."},
{id:"e2",num:"Evidence 02",title:"An Orderly Abandonment",date:"Primary account · August 1590",sourceType:"Primary Account",text:"White found the settlement deserted. National Park Service summaries of his account note that the buildings appeared dismantled rather than violently destroyed. White did not report clear signs of a battle at the colony site.",observation:"The physical condition of the settlement fits an organized departure better than sudden destruction at that location.",question:"Which interpretation fits the site condition best?",choices:["The colonists may have packed up and moved deliberately.","A battle at Roanoke is proven beyond doubt.","A hurricane unquestionably killed everyone at the settlement.","The buildings were untouched and fully occupied."],answer:0,explain:"Dismantled buildings and the lack of obvious battle damage make an organized relocation plausible, though they do not reveal the colonists’ final destination."},
{id:"e3",num:"Evidence 03",title:"Three Years Without Rescue",date:"Historical context · 1587–1590",sourceType:"Context",text:"White left for England in 1587 expecting to return with supplies. The conflict with Spain and the Spanish Armada disrupted English shipping. He did not reach Roanoke again until August 1590.",observation:"The colonists endured a much longer period without the expected resupply and leadership than they had planned.",question:"Why does the delay matter to the case?",choices:["It increased pressure to relocate, seek food, or rely on nearby communities.","It proves the colonists sailed back to England.","It means the colony had unlimited supplies.","It confirms a Spanish attack."],answer:0,explain:"The delay created strong survival pressures, but it does not identify one single outcome."},
{id:"e4",num:"Evidence 04",title:"The Croatoan Connection",date:"Relationship evidence · 1580s",sourceType:"Historical Context",text:"Croatoan was both the name of a place, now associated with Hatteras Island, and of an Indigenous community. Manteo, a Croatoan man, had traveled with the English and maintained a friendly relationship with them. White believed the carving meant the colonists had moved toward Croatoan.",observation:"The named destination was not random; the colonists already had a known human connection there.",question:"How should this clue affect your theory?",choices:["It makes relocation toward Croatoan more plausible.","It proves every colonist remained together permanently.","It proves the colonists never left Roanoke.","It eliminates every other possible destination."],answer:0,explain:"The relationship and the carving strengthen the Croatoan theory, but they do not provide final proof of what happened to all 117 colonists."},
{id:"e5",num:"Evidence 05",title:"The Inland Instruction",date:"Map + archaeology · later investigation",sourceType:"Map & Archaeology",text:"White had instructed the colonists to move about 50 miles inland if they left Roanoke. A patched area on his map later revealed a fort-like symbol near present-day Bertie County. Archaeologists have found English-period objects in that region, including pottery and metal items.",observation:"There is a second plausible relocation route: inland along the Albemarle Sound.",question:"What is the strongest historical reading of this evidence?",choices:["It supports an inland-relocation possibility, but the artifacts are not definitively tied to the Lost Colony.","It proves all colonists lived permanently in Bertie County.","The map symbol has no relevance at all.","The finds prove the colony stayed on Roanoke Island."],answer:0,explain:"The evidence is suggestive, not conclusive. Trade or earlier English contact could also explain some artifacts."},
{id:"e6",num:"Evidence 06",title:"Hatteras Artifacts",date:"Archaeology · modern investigations",sourceType:"Archaeology",text:"English-period artifacts have also been found on Hatteras Island, associated with Croatoan territory. The National Park Service notes that these finds are intriguing, but no graves, buildings, or village site have been definitively linked to the lost colonists, and trade could explain some objects.",observation:"Archaeology keeps the Croatoan theory alive, but the chain of proof remains incomplete.",question:"How should an investigator treat this clue?",choices:["As supporting evidence with important uncertainty.","As absolute proof that every colonist assimilated there.","As proof the Croatoan community attacked the colony.","As meaningless because artifacts can never inform history."],answer:0,explain:"Good historical reasoning distinguishes evidence that supports a theory from evidence that proves it."}
],
theories:[
{id:"croatoan",title:"Relocated to Croatoan",desc:"The colonists moved toward Croatoan/Hatteras and may have lived with or near the Croatoan community.",strong:["e1","e2","e3","e4","e6"],weak:["e5"],summary:"This theory fits the carved destination, the orderly-looking abandonment, White’s own interpretation, known ties to Manteo, and some later archaeological finds. The major limitation is that no site or remains have been definitively tied to all of the colonists."},
{id:"inland",title:"Relocated Inland",desc:"The colonists followed White’s earlier instruction and moved inland along the Albemarle Sound.",strong:["e2","e3","e5"],weak:["e1","e4","e6"],summary:"This theory fits White’s inland instruction, the map clue, and English-period finds in Bertie County. The major problem is that the Croatoan carving points elsewhere, and the inland artifacts remain inconclusive."},
{id:"crisis",title:"Destroyed by Crisis or Attack",desc:"Famine, disease, hurricane, warfare, or another crisis caused the colony to collapse.",strong:["e3"],weak:["e1","e2","e4","e5","e6"],summary:"The colonists faced genuine dangers, but the surviving evidence at Roanoke does not clearly show a catastrophic event at the settlement. The carved message and dismantled structures complicate a sudden-destruction explanation."},
{id:"split",title:"The Group Split",desc:"Different groups may have gone to different destinations, which could explain clues pointing toward both Croatoan and inland locations.",strong:["e1","e2","e3","e4","e5","e6"],weak:[],summary:"A split-group theory can account for evidence pointing in more than one direction. Its weakness is that there is no surviving document confirming a division of the colonists."}
],
sources:[
{label:"National Park Service — 1590 Rescue Voyage",url:"https://www.nps.gov/fora/learn/historyculture/1590-rescue-voyage.htm"},
{label:"National Park Service — Major Theories of the Lost Colony",url:"https://www.nps.gov/fora/learn/historyculture/major-theories-of-the-lost-colony.htm"},
{label:"National Park Service — Archaeology at Fort Raleigh",url:"https://www.nps.gov/articles/000/the-history-of-archeology-in-fort-raleigh-national-historic-site.htm"},
{label:"National Park Service — 1587: The Lost Colony",url:"https://www.nps.gov/fora/learn/historyculture/1587-the-lost-colony.htm"}
]
};