window.ESCAPE_CONFIG={
title:"Escape the Great Depression",brief:"The Great Depression was not one bad day on Wall Street. It was a prolonged economic crisis involving banking failures, unemployment, falling demand, business collapse, debt, migration, and major changes in government policy.",
objectiveTitle:"Navigate the Economic Crisis",objective:"Use evidence about banks, work, migration, and New Deal policy to move through four crisis points and unlock the recovery file.",
stages:[
{type:"choice",title:"The Bank Door",scene:"A sign announces that the local bank has closed and depositors cannot immediately access their savings.",clueTitle:"Clue: Banking Crisis",clue:"During the early 1930s, thousands of U.S. banks failed. Before federal deposit insurance, many depositors could lose savings when a bank collapsed.",hint:"The danger was not limited to investors in the stock market.",question:"What did bank failures do to the wider economy?",choices:["They destroyed savings, restricted credit, and deepened fear and contraction.","They guaranteed more loans for businesses.","They affected only wealthy stock traders.","They immediately increased consumer spending."],answer:0,wrong:"Think about savings, credit, and public confidence.",danger:12,reward:{icon:"🏦",item:"Bank Ledger",note:"Evidence of financial-system collapse."},explain:"Bank failures damaged household savings, credit, business activity, and confidence."},
{type:"code",title:"The Inauguration File",scene:"A policy memo marks the year Franklin D. Roosevelt took office and the first New Deal measures began.",clueTitle:"Clue: New Administration",clue:"Franklin D. Roosevelt took office in 1933 and immediately launched a series of emergency banking and relief measures.",hint:"Enter the year in the clue.",question:"Enter the year Roosevelt took office.",answer:"1933",numeric:true,placeholder:"4-digit year",wrong:"The year is stated directly in the clue.",danger:10,reward:{icon:"📁",item:"New Deal File",note:"Marks a major shift in federal policy."},explain:"Roosevelt's 1933 inauguration began the first wave of New Deal legislation and emergency programs."},
{type:"sequence",title:"The Relief Office",scene:"A wall chart shows how an economic downturn can become self-reinforcing.",clueTitle:"Clue: Depression Spiral",clue:"When businesses lose customers, they cut production and jobs. Unemployed workers then have less income to spend, which can reduce demand even further.",hint:"Follow the chain from falling demand to deeper contraction.",question:"Tap the sequence in order.",items:["Demand falls","Businesses cut production","Workers lose jobs or income","Household spending falls further"],answer:[0,1,2,3],wrong:"Start with falling demand, then follow the effect on firms and workers.",danger:12,reward:{icon:"📉",item:"Depression Cycle Chart",note:"Shows how contraction can reinforce itself."},explain:"Economic downturns can deepen through feedback loops involving demand, production, employment, and income."},
{type:"choice",title:"The Migration Station",scene:"A map shows families leaving parts of the Great Plains during the Dust Bowl years.",clueTitle:"Clue: Environmental and Economic Crisis",clue:"Drought, soil erosion, farm debt, and collapsing agricultural prices pushed many families from the Great Plains. Some migrated west seeking work and stability.",hint:"Do not treat the Dust Bowl as only a weather story.",question:"What is the strongest interpretation of Dust Bowl migration?",choices:["Environmental disaster interacted with economic hardship and farm vulnerability.","Migration happened because western states offered guaranteed jobs.","Only urban bank failures mattered.","The drought had no connection to farming."],answer:0,wrong:"The clue describes both environmental and economic pressures.",danger:12,reward:{icon:"🧳",item:"Migration Ticket",note:"Evidence of displacement during the Depression."},explain:"Dust Bowl migration grew from the interaction of drought, soil problems, falling prices, debt, and limited opportunity."}
],
finalLock:{icon:"📂",question:"Which statement best explains the Great Depression?",choices:["It was a complex economic crisis involving finance, demand, employment, agriculture, and policy—not a single-cause event.","The stock-market crash alone explains every part of the Depression.","The crisis affected only banks.","Government policy played no role in the response."],answer:0,wrong:"Use all four recovered evidence items.",explain:"The Depression was a system-wide crisis whose causes and consequences extended far beyond the 1929 stock-market crash."},
closing:"You escaped by treating the Great Depression as an interconnected crisis. Banking, unemployment, migration, demand, and government policy all shaped the experience of the 1930s.",
takeaways:["Bank failures deepened the crisis.","Economic contraction can reinforce itself.","The New Deal expanded federal intervention.","The Dust Bowl combined environmental and economic pressures."],
sources:[{label:"Federal Reserve History — Great Depression",url:"https://www.federalreservehistory.org/essays/great-depression"},{label:"National Archives — New Deal",url:"https://www.archives.gov/research/alic/reference/new-deal.html"},{label:"Library of Congress — Dust Bowl Migration",url:"https://www.loc.gov/classroom-materials/united-states-history-primary-source-timeline/great-depression-and-world-war-ii-1929-1945/dust-bowl/"}]
};