window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Scientists",brief:"Identify scientists from discoveries, experiments, instruments, theories, and the institutions in which scientific knowledge developed.",question:"Can you identify the scientist before all three clues are revealed?",
people:[
{name:"Galileo Galilei",roundTitle:"Identity 1 · Observation and Motion",clues:["I was an Italian scientist of the early 17th century.","I used improved telescopes to observe the Moon, Jupiter, and other celestial objects.","My support for heliocentrism brought me into conflict with Church authorities."],options:["Galileo Galilei","Nicolaus Copernicus","Johannes Kepler","Tycho Brahe"],answer:0,explain:"Galileo combined mathematical analysis, experiment, and telescopic observation in ways that transformed early modern science."},
{name:"Isaac Newton",roundTitle:"Identity 2 · Motion and Gravity",clues:["I was an English mathematician and natural philosopher.","I developed laws of motion and a mathematical description of universal gravitation.","My Principia was published in 1687."],options:["Robert Hooke","Isaac Newton","Edmond Halley","Francis Bacon"],answer:1,explain:"Newton's mathematical laws unified terrestrial and celestial motion within one framework."},
{name:"Charles Darwin",roundTitle:"Identity 3 · Evolution",clues:["I traveled aboard HMS Beagle.","I developed a theory explaining evolutionary change through natural selection.","On the Origin of Species appeared in 1859."],options:["Alfred Russel Wallace","Charles Darwin","Gregor Mendel","Jean-Baptiste Lamarck"],answer:1,explain:"Darwin developed a powerful explanation for biological evolution through natural selection."},
{name:"Marie Curie",roundTitle:"Identity 4 · Radioactivity",clues:["I was born in Poland and conducted much of my scientific work in France.","My research focused on radioactivity.","I became the first person to receive Nobel Prizes in two different scientific fields."],options:["Marie Curie","Lise Meitner","Rosalind Franklin","Emmy Noether"],answer:0,explain:"Curie's work on radioactivity transformed physics and chemistry and had major medical applications."},
{name:"Katherine Johnson",roundTitle:"Identity 5 · Spaceflight Mathematics",clues:["I was a mathematician who worked for NACA and NASA.","My calculations helped verify trajectories for crewed U.S. space missions.","My career became widely known through the story Hidden Figures."],options:["Katherine Johnson","Dorothy Vaughan","Mary Jackson","Margaret Hamilton"],answer:0,explain:"Johnson's orbital-mechanics calculations supported major NASA missions, including John Glenn's orbital flight."}
],
closing:"Scientific discovery is built through evidence, mathematics, experiment, instruments, institutions, debate, and often collaboration across generations.",
takeaways:["Scientific ideas change through evidence.","Instruments can make new observations possible.","Credit in science can be unevenly distributed.","Major discoveries usually depend on earlier work."]
};