window.MAP_QUEST_CONFIG={
title:"Ancient Civilizations Map Hunt",brief:"Many early civilizations developed in environments where rivers supported agriculture, transport, settlement, and state formation—but every river valley produced a different historical system.",
question:"Use river, landform, and regional clues to identify the civilization.",
rounds:[
{title:"Between Two Rivers",prompt:"Identify the civilization zone whose Greek name means 'between the rivers.'",clueTitle:"Clue: Tigris and Euphrates",clue:"Cities such as Ur and Uruk developed in the fertile but environmentally challenging plains between the Tigris and Euphrates.",places:[{name:"Mesopotamia",detail:"Tigris–Euphrates basin"},{name:"Egypt",detail:"Nile Valley"},{name:"Indus civilization",detail:"Indus basin"},{name:"Shang China",detail:"Yellow River region"}],answer:0,explain:"Mesopotamian civilizations developed in the river systems of present-day Iraq and neighboring regions."},
{title:"The Nile Corridor",prompt:"Choose the civilization whose agricultural life depended on the Nile and a narrow fertile valley surrounded by desert.",clueTitle:"Clue: River Through Desert",clue:"Annual Nile flooding supported agriculture while surrounding deserts helped shape settlement patterns and communication.",places:[{name:"Ancient Egypt",detail:"Nile Valley and Delta"},{name:"Mesopotamia",detail:"Tigris–Euphrates"},{name:"Indus civilization",detail:"South Asia"},{name:"Minoan Crete",detail:"Aegean Sea"}],answer:0,explain:"Ancient Egyptian settlement clustered along the Nile Valley and Delta, where water and fertile soils supported dense populations."},
{title:"Planned Cities of the Indus",prompt:"Identify the civilization associated with cities such as Harappa and Mohenjo-daro.",clueTitle:"Clue: Indus River Basin",clue:"Large urban centers developed in northwestern South Asia with planned streets, drainage systems, craft production, and long-distance trade.",places:[{name:"Indus civilization",detail:"Indus and related river systems"},{name:"Shang China",detail:"Yellow River region"},{name:"Egypt",detail:"Nile Valley"},{name:"Olmec",detail:"Mesoamerica"}],answer:0,explain:"Harappa and Mohenjo-daro were major urban centers of the Indus civilization."},
{title:"Bronze Age China",prompt:"Find the civilization associated with Anyang and powerful Bronze Age kings in the Yellow River region.",clueTitle:"Clue: Oracle Bones",clue:"Archaeological evidence at Anyang includes elite tombs, bronze production, palatial remains, and oracle-bone inscriptions.",places:[{name:"Shang dynasty",detail:"Yellow River region"},{name:"Indus civilization",detail:"South Asia"},{name:"Sumer",detail:"Mesopotamia"},{name:"Old Kingdom Egypt",detail:"Nile Valley"}],answer:0,explain:"The Shang dynasty is strongly associated with Anyang and some of the earliest extensive written evidence from China."}
],
challenge:{question:"Why did rivers matter to many early civilizations?",choices:["Rivers automatically created civilizations.","Rivers could support water, farming, transport, trade, and dense settlement, but societies still developed through human institutions, technology, conflict, belief, and adaptation.","Every early civilization depended on identical flood patterns.","Civilizations could exist only beside rivers."],answer:1,explain:"River environments created important opportunities and risks, but social and political development was never automatic."},
closing:"Ancient maps are most useful when location is connected to environment, settlement, technology, and political organization.",
takeaways:["River valleys supported dense settlement in many regions.","Flood patterns differed from river to river.","Urban planning can reveal social organization.","Geography shaped—but did not determine—civilization."]
};