window.MAP_QUEST_CONFIG={
title:"Battlefields Quest",brief:"Battlefields are geographic problems. Rivers, ridges, roads, cities, coastlines, weather, and distance shape what armies can do.",
question:"Use terrain and location clues to identify the battlefield.",
rounds:[
{title:"A Narrow Greek Pass",prompt:"Find the battle fought at a narrow pass where terrain limited the size advantage of a much larger Persian army.",clueTitle:"Clue: Mountain Meets Sea",clue:"In 480 BCE, Greek forces made a stand at a narrow route between mountains and the sea during the Persian invasion.",places:[{name:"Thermopylae",detail:"Central Greece"},{name:"Marathon",detail:"Attica"},{name:"Actium",detail:"Western Greece"},{name:"Gaugamela",detail:"Mesopotamia"}],answer:0,explain:"The narrow terrain at Thermopylae temporarily reduced the tactical advantage of Persian numerical superiority."},
{title:"A Ridge in Pennsylvania",prompt:"Identify the Civil War battlefield where high ground and ridgelines became crucial over three days in 1863.",clueTitle:"Clue: Cemetery Ridge",clue:"Union forces held a curved defensive position on high ground while Confederate attacks struck both flanks and the center.",places:[{name:"Gettysburg",detail:"Pennsylvania"},{name:"Vicksburg",detail:"Mississippi"},{name:"Antietam",detail:"Maryland"},{name:"Shiloh",detail:"Tennessee"}],answer:0,explain:"At Gettysburg, ridges, hills, roads, and lines of approach strongly shaped the battle."},
{title:"City on the Volga",prompt:"Choose the World War II battle fought for a major industrial city on the Volga River.",clueTitle:"Clue: Urban War and Supply",clue:"The city became a brutal battlefield in 1942–43, while Soviet forces later encircled the German Sixth Army.",places:[{name:"Stalingrad",detail:"Volga River"},{name:"El Alamein",detail:"Egypt"},{name:"Monte Cassino",detail:"Italy"},{name:"Dunkirk",detail:"France"}],answer:0,explain:"Stalingrad's industrial and river geography mattered strategically, while urban terrain shaped intense close combat."},
{title:"Channel Crossing",prompt:"Identify the 1944 Allied operation whose geography depended on beaches, tides, ports, and a narrow sea crossing.",clueTitle:"Clue: Normandy Coast",clue:"Allied armies crossed the English Channel and landed on five major beaches in northern France on June 6, 1944.",places:[{name:"Normandy",detail:"Northern France"},{name:"Sicily",detail:"Mediterranean"},{name:"Anzio",detail:"Italy"},{name:"Gallipoli",detail:"Dardanelles"}],answer:0,explain:"The Normandy invasion depended on weather, tides, beach conditions, naval support, and the short cross-Channel distance from Britain."}
],
challenge:{question:"What is the best way to use geography when studying battles?",choices:["Terrain determines the winner automatically.","Terrain shapes options, movement, supply, visibility, and defense, but leadership, numbers, technology, morale, and chance also matter.","Maps are useful only for locating the nearest city.","Geography matters only in ancient warfare."],answer:1,explain:"Battlefield geography constrains and enables military choices without mechanically determining outcomes."},
closing:"Battle maps become more useful when terrain is treated as part of the decision-making environment.",
takeaways:["Narrow terrain can change numerical advantage.","High ground can shape defense and observation.","Cities create different tactical problems than open fields.","Amphibious operations depend heavily on coastlines, weather, and logistics."]
};