window.MAP_QUEST_CONFIG={
title:"Colonies Challenge",brief:"Colonial settlements were never randomly placed. Harbors, rivers, climate, Indigenous homelands, labor systems, military strategy, and access to trade all shaped where colonies developed.",
question:"Use each geographic clue to locate the colonial setting that best fits.",
rounds:[
{title:"Chesapeake Settlement",prompt:"Locate the English colony founded on a river in the Chesapeake region in 1607.",clueTitle:"Clue: Tidewater Virginia",clue:"The settlement sat inland from the Atlantic on the James River, where ships could reach it but marshy conditions and disease created major problems.",places:[{name:"Jamestown",detail:"Virginia / Chesapeake"},{name:"Quebec",detail:"St. Lawrence River"},{name:"Havana",detail:"Cuba"},{name:"Plymouth",detail:"New England"}],answer:0,explain:"Jamestown's river location supported Atlantic access but also exposed settlers to environmental and health challenges."},
{title:"St. Lawrence Gateway",prompt:"Choose the French colonial center positioned on the St. Lawrence River.",clueTitle:"Clue: River to the Interior",clue:"This settlement became a key point in French North American trade and diplomacy because the river provided access deep into the continent.",places:[{name:"Quebec",detail:"St. Lawrence River"},{name:"Charleston",detail:"South Carolina coast"},{name:"Lima",detail:"Pacific South America"},{name:"Boston",detail:"Massachusetts Bay"}],answer:0,explain:"Quebec's position on the St. Lawrence made it a strategic gateway for trade, diplomacy, and movement inland."},
{title:"Caribbean Sugar Colony",prompt:"Identify the island colony whose warm climate and plantation economy became heavily tied to sugar and enslaved labor.",clueTitle:"Clue: Atlantic Plantation Zone",clue:"By the seventeenth century, this English colony had become one of the wealthiest sugar-producing islands in the Caribbean.",places:[{name:"Barbados",detail:"Eastern Caribbean"},{name:"Newfoundland",detail:"North Atlantic"},{name:"Pennsylvania",detail:"Mid-Atlantic North America"},{name:"Quebec",detail:"St. Lawrence Valley"}],answer:0,explain:"Barbados became a major sugar colony whose plantation economy relied on the brutal exploitation of enslaved Africans."},
{title:"Silver in the Andes",prompt:"Locate the Spanish colonial mining center built near one of the world's richest silver deposits.",clueTitle:"Clue: High-Altitude Mining",clue:"This city grew more than 4,000 meters above sea level in the Andes beside Cerro Rico, whose silver fed global trade.",places:[{name:"Potosí",detail:"Andean Bolivia"},{name:"Cartagena",detail:"Caribbean coast"},{name:"Manila",detail:"Philippines"},{name:"Veracruz",detail:"Gulf of Mexico"}],answer:0,explain:"Potosí became a major Spanish colonial mining center because of the extraordinary silver deposits of Cerro Rico."}
],
challenge:{question:"What is the strongest way to read colonial maps?",choices:["As empty land waiting for European settlement.","As contested spaces shaped by Indigenous societies, environment, trade, coercion, labor systems, and imperial rivalry.","Only by memorizing colonial capitals.","By assuming every colony developed for the same reason."],answer:1,explain:"Colonial geography must include the peoples already living there and the systems of power imposed through settlement and empire."},
closing:"Colonial geography reveals how empire depended on access, extraction, labor, settlement, and strategic location.",
takeaways:["Rivers and harbors shaped settlement.","Climate influenced colonial economies.","Indigenous homelands were not empty spaces.","Resource extraction tied local places to global systems."]
};