window.ESCAPE_CONFIG={
title:"Escape the Trenches",brief:"The Western Front was shaped by trenches, artillery, machine guns, mud, wire, logistics, and rapidly changing tactics. Your mission is to move through a trench sector by reading battlefield evidence correctly.",
objectiveTitle:"Cross the Sector",objective:"Solve four tactical-history locks and recover the evidence needed to understand why trench warfare became so deadly and difficult to break.",
stages:[
{type:"choice",title:"The Trench Map",scene:"A map shows opposing trench systems separated by exposed ground.",clueTitle:"Clue: No Man's Land",clue:"The space between opposing trench lines became known as no man's land. It could be covered by shell craters, wire, mud, and fields of fire.",hint:"The danger comes from exposure between fortified positions.",question:"What made crossing no man's land so dangerous?",choices:["Attackers were exposed to artillery, machine-gun fire, wire, and difficult terrain.","It was protected by permanent peace agreements.","It was always empty and safe.","Trenches eliminated the need for defensive weapons."],answer:0,wrong:"Think about what happens when troops leave cover and cross open ground.",danger:12,reward:{icon:"🗺️",item:"Sector Map",note:"Shows the exposed ground between trench systems."},explain:"No man's land concentrated multiple dangers in a narrow space between heavily defended lines."},
{type:"code",title:"The War Date Lock",scene:"A field telephone note marks the year the First World War began.",clueTitle:"Clue: War Begins",clue:"World War I began in Europe in 1914 after the July Crisis escalated from the assassination of Archduke Franz Ferdinand into a wider war.",hint:"Enter the four-digit year.",question:"Enter the year World War I began.",answer:"1914",numeric:true,placeholder:"4-digit year",wrong:"The clue identifies the year directly.",danger:10,reward:{icon:"☎️",item:"Field Message",note:"Places the trench sector in the wider war."},explain:"The war began in 1914 and expanded through alliance commitments, mobilization, and political decisions."},
{type:"sequence",title:"The Assault Plan",scene:"A tactical note shows how an infantry assault was supposed to work.",clueTitle:"Clue: Artillery and Infantry",clue:"Many offensives began with artillery bombardment intended to damage defenses, followed by infantry leaving their trenches and advancing. Defenders often survived bombardment in dugouts and returned to firing positions.",hint:"Put the basic assault sequence in order.",question:"Tap the stages in order.",items:["Artillery bombardment begins","Infantry leaves the trench","Attackers cross no man's land","Defenders respond from surviving positions"],answer:[0,1,2,3],wrong:"Start with bombardment, then the infantry advance.",danger:14,reward:{icon:"💥",item:"Artillery Schedule",note:"Shows why coordination mattered."},explain:"The sequence highlights a major problem: bombardment did not always destroy defenses, leaving advancing infantry exposed."},
{type:"choice",title:"The Technology Gate",scene:"The final gate asks why tactical systems changed over the course of the war.",clueTitle:"Clue: Adaptation",clue:"Armies experimented with creeping barrages, tanks, aircraft, improved communications, infiltration tactics, and combined-arms coordination as they searched for ways to overcome trench defenses.",hint:"The war did not remain tactically frozen forever.",question:"What does this evidence show?",choices:["Armies adapted tactics and technology in response to trench warfare.","No new tactics developed after 1914.","Tanks immediately made trenches irrelevant everywhere.","Aircraft had no military role."],answer:0,wrong:"Look for the pattern of adaptation in the clue.",danger:12,reward:{icon:"⚙️",item:"Tactical Notes",note:"Evidence of wartime adaptation."},explain:"Trench warfare encouraged rapid tactical and technological experimentation, even though breakthroughs remained costly."}
],
finalLock:{icon:"🚧",question:"Why was trench warfare so difficult to break?",choices:["Defensive firepower, field fortifications, terrain, logistics, and imperfect coordination gave defenders major advantages.","Soldiers refused to use modern weapons.","Trenches were decorative rather than military.","Only weather mattered."],answer:0,wrong:"Combine the map, artillery, assault sequence, and adaptation clues.",explain:"The stalemate emerged from the interaction of technology, terrain, fortification, logistics, and doctrine."},
closing:"You crossed the sector by understanding trench warfare as a system. The battlefield was shaped not by one weapon alone, but by the interaction of defense, firepower, terrain, communication, and adaptation.",
takeaways:["No man's land exposed attackers to concentrated fire.","Artillery and infantry had to coordinate.","Defenders could survive bombardments in deep positions.","World War I tactics evolved significantly over time."],
sources:[{label:"Imperial War Museums — Trench Warfare",url:"https://www.iwm.org.uk/history/what-was-trench-warfare"},{label:"National WWI Museum — Online Collections",url:"https://www.theworldwar.org/learn/educator-resource"}]
};