window.CASE_FILE_CONFIG={
title:"The Underground Railroad File",caseNumber:"06",location:"United States & Canada · 19th century",
brief:"The Underground Railroad was not a physical railroad and it was not one centrally controlled organization. It was a changing pattern of self-emancipation, local knowledge, family decisions, guides, safe places, transportation, and people willing to take enormous risks.",
question:"How did the Underground Railroad actually work—and which popular myths distort the history?",
assignment:"Investigate movement, law, geography, self-emancipation, Harriet Tubman's work, and later myths. Keep freedom seekers at the center of the story.",
midCaseTwist:{icon:"🧭",title:"There Was No Single Route",text:"The evidence does not point to one secret line north. Routes stretched through multiple regions and destinations, and many freedom seekers traveled without a conductor. The 'railroad' metaphor can help—but it can also hide the complexity."},
crossExam:{question:"Which statement best reflects current National Park Service interpretation?",choices:["The Underground Railroad was a single organization run by Harriet Tubman.","It was a flexible set of self-emancipation efforts and assistance networks; many people traveled without formal conductors, and routes varied widely.","Quilt patterns are documented in first-hand accounts as the main navigation system.","Every freedom seeker traveled to Canada."],answer:1,explain:"NPS emphasizes self-emancipation, varied routes, local networks, and the fact that many freedom seekers completed their journeys without conductors."},
closingCaution:"Because escape depended on secrecy, the surviving record is incomplete. Avoid replacing missing documentation with attractive legends. The strongest history centers freedom seekers and clearly distinguishes documented practices from later folklore.",
evidence:[
{id:"e1",num:"Evidence 01",title:"Not a Literal Railroad",date:"Historical framework",sourceType:"Definition",text:"The National Park Service defines the Underground Railroad as resistance to enslavement through escape and flight, together with people and places that sometimes assisted freedom seekers.",observation:"The railroad language was a metaphor for a decentralized movement, not a physical transportation system.",question:"What should an investigator reject immediately?",choices:["The idea that it was literally one hidden railroad line.","The fact that some people used trains.","The existence of escape networks.","The role of freedom seekers themselves."],answer:0,explain:"Railroad terminology described roles and movement, but there was no single underground railway."},
{id:"e2",num:"Evidence 02",title:"Self-Emancipation Came First",date:"Movement pattern",sourceType:"NPS Interpretation",text:"NPS notes that many freedom seekers began and completed their journeys without a conductor. Organized assistance grew over time, but escape itself depended first on the decisions and actions of enslaved people.",observation:"The story cannot be reduced to rescuers helping passive passengers.",question:"What does this evidence change?",choices:["It centers the agency and planning of freedom seekers.","It proves conductors never existed.","It means nobody ever received assistance.","It shows escape was easy."],answer:0,explain:"Assistance mattered, but self-emancipation is central to understanding the movement."},
{id:"e3",num:"Evidence 03",title:"Routes Like a Spider Web",date:"Geography · 19th century",sourceType:"Geographic Evidence",text:"NPS describes routes extending up the East Coast, through the Appalachians and Midwest, and toward destinations including northern states, Canada, Mexico, Spanish Florida, the Caribbean, and elsewhere.",observation:"There was no single northbound route or universal destination.",question:"What is the strongest geographic conclusion?",choices:["The Underground Railroad was a flexible network shaped by location and opportunity.","Every route followed the same road.","Canada was the only destination.","The movement existed only in one state."],answer:0,explain:"Different people made different journeys depending on geography, law, contacts, and opportunity."},
{id:"e4",num:"Evidence 04",title:"The Fugitive Slave Act Raises the Risk",date:"Federal law · 1850",sourceType:"Legal Context",text:"The Fugitive Slave Act of 1850 strengthened legal mechanisms for recapturing freedom seekers and increased danger even in free states. NPS notes that many people continued farther to Canada after the law.",observation:"Law changed the geography and risk calculations of escape.",question:"Why does this law matter to the case?",choices:["It made northern free states less secure for many freedom seekers.","It ended slavery nationwide.","It made escape legally protected everywhere.","It eliminated the need for secrecy."],answer:0,explain:"Legal danger did not stop escape, but it changed routes, destinations, and the risks faced by freedom seekers and allies."},
{id:"e5",num:"Evidence 05",title:"Harriet Tubman's Documented Work",date:"Maryland and beyond · 1850s",sourceType:"Biography",text:"NPS estimates that Harriet Tubman made about thirteen rescue trips and directly assisted roughly seventy people, including family members, while also giving instructions that helped others escape.",observation:"Tubman was an extraordinary conductor, but the movement involved far more people and places than one individual.",question:"What is the most responsible interpretation?",choices:["Tubman was a major conductor within a much larger movement.","Tubman personally ran the entire Underground Railroad.","Tubman never returned to Maryland.","Only people she personally guided escaped."],answer:0,explain:"Her accomplishments are remarkable without turning the Underground Railroad into a one-person system."},
{id:"e6",num:"Evidence 06",title:"The Quilt Code Problem",date:"Historical method",sourceType:"Myth Check",text:"The National Park Service states that researchers have not found documented first-hand accounts of freedom seekers or allies using the popular 'quilt code' story, and some patterns associated with the legend did not exist until after the Civil War.",observation:"A compelling story is not automatically a documented historical practice.",question:"How should historians treat the quilt-code claim?",choices:["As a later story that lacks documented first-hand support.","As proven fact because it is widely repeated.","As the main navigation system used by Tubman.","As evidence that written sources are useless."],answer:0,explain:"Historical method requires distinguishing repeated folklore from claims supported by contemporary evidence."}
],
theories:[
{id:"flexible",title:"A Flexible Movement of Self-Emancipation and Aid",desc:"Freedom seekers drove their own escapes while decentralized networks, guides, safe places, and local knowledge sometimes provided assistance.",strong:["e1","e2","e3","e4","e5","e6"],weak:[],summary:"This interpretation best fits current NPS scholarship: varied routes, self-emancipation, decentralized help, changing legal risk, and careful separation of documented practices from later myths."},
{id:"central",title:"One Centrally Managed Secret Organization",desc:"A single leadership structure controlled fixed routes, stations, and conductors across the country.",strong:[],weak:["e1","e2","e3"],summary:"The surviving evidence points to decentralized, local, and changing networks rather than one national command structure."},
{id:"tubman",title:"Harriet Tubman Ran the Entire System",desc:"Tubman personally organized most Underground Railroad escapes.",strong:["e5"],weak:["e1","e2","e3"],summary:"Tubman was one of the best-known and most effective conductors, but the movement predated her work and involved many freedom seekers and allies."},
{id:"folklore",title:"Popular Legends Are Reliable Operational Evidence",desc:"Stories such as a standardized quilt code accurately describe how most escapes were organized.",strong:[],weak:["e6"],summary:"The historical record does not support treating popular quilt-code claims as documented first-hand practice."}
],
sources:[
{label:"NPS — What Is the Underground Railroad?",url:"https://home.nps.gov/subjects/undergroundrailroad/what-is-the-underground-railroad.htm"},
{label:"NPS — Underground Railroad FAQ",url:"https://www.nps.gov/subjects/undergroundrailroad/frequently-asked-questions.htm"},
{label:"NPS — Harriet Tubman FAQ",url:"https://www.nps.gov/hart/faqs.htm"},
{label:"NPS — Harriet Tubman and the Underground Railroad",url:"https://home.nps.gov/articles/harriet-tubman-and-the-underground-railroad.htm"}
]};