window.MAP_QUEST_CONFIG={
title:"Migration Paths",brief:"Migration connects geography to human decisions. People move because of opportunity, coercion, violence, environment, family networks, law, and economic change.",
question:"Use push-pull clues and routes to identify the migration pattern.",
rounds:[
{title:"Bantu-Speaking Expansion",prompt:"Identify the long-term movement of Bantu-speaking communities across much of sub-Saharan Africa.",clueTitle:"Clue: Languages, Farming, Ironworking",clue:"Over many centuries, Bantu-speaking communities moved eastward and southward from parts of west-central Africa, spreading languages and cultural practices across a vast region.",places:[{name:"Bantu migrations",detail:"Central, eastern, and southern Africa"},{name:"Great Migration",detail:"United States"},{name:"Austronesian expansion",detail:"Pacific and Indian Ocean islands"},{name:"Viking settlement",detail:"North Atlantic"}],answer:0,explain:"Bantu-speaking communities moved over long periods, producing one of the world's largest language-family distributions."},
{title:"Black Americans Move North and West",prompt:"Identify the migration that reshaped U.S. cities in the twentieth century.",clueTitle:"Clue: Leaving the Jim Crow South",clue:"Millions of Black Americans moved from the rural South to northern, midwestern, and western cities seeking greater opportunity and escaping racial oppression.",places:[{name:"Great Migration",detail:"U.S. South to North and West"},{name:"Dust Bowl migration",detail:"Great Plains to West"},{name:"Oregon Trail",detail:"19th-century western migration"},{name:"Atlantic immigration",detail:"Europe to U.S."}],answer:0,explain:"The Great Migration transformed cities such as Chicago, Detroit, New York, Los Angeles, and many others."},
{title:"Indentured Labor Across Empire",prompt:"Choose the migration system that moved large numbers of South Asian workers after slavery was abolished in parts of the British Empire.",clueTitle:"Clue: Contracts Across Oceans",clue:"Workers traveled under indenture contracts to plantations and colonies in the Caribbean, Africa, the Indian Ocean, and the Pacific.",places:[{name:"Indian indentured migration",detail:"South Asia to imperial labor destinations"},{name:"Bantu migrations",detail:"Sub-Saharan Africa"},{name:"Great Migration",detail:"United States"},{name:"Viking settlement",detail:"North Atlantic"}],answer:0,explain:"Indenture created large South Asian diasporas in places including the Caribbean, Mauritius, Fiji, and southern Africa."},
{title:"Dust Bowl Movement",prompt:"Identify the migration associated with drought, soil erosion, farm crisis, and the Great Depression.",clueTitle:"Clue: Plains to California",clue:"During the 1930s, many families left drought-stricken parts of the Great Plains and moved west in search of work.",places:[{name:"Dust Bowl migration",detail:"Great Plains toward western states"},{name:"Great Migration",detail:"Black migration from U.S. South"},{name:"California Gold Rush",detail:"Mid-19th century"},{name:"Mormon migration",detail:"Great Basin"}],answer:0,explain:"Dust Bowl migration reflected both environmental disaster and severe economic hardship."}
],
challenge:{question:"What do push-pull models help historians do?",choices:["Reduce every migration to one cause.","Organize pressures that encourage people to leave and attractions that draw them elsewhere, while still recognizing networks, coercion, law, and individual choice.","Prove all migration is voluntary.","Show geography has no role in migration."],answer:1,explain:"Push-pull language can be useful, but real migration decisions are usually more complex than a simple two-column model."},
closing:"Migration maps are stories of movement, constraint, adaptation, and cultural change.",
takeaways:["Migration may be voluntary, forced, or somewhere between.","Family and community networks can shape routes.","Law and racial systems can redirect movement.","Environmental and economic pressures often interact."]
};