window.WHO_IN_TIME_CONFIG={
title:"Who Am I? Leaders",brief:"Identify major historical leaders from geography, decisions, institutions, conflict, and the legacies associated with their rule.",question:"Can you identify the leader before all three clues are revealed?",
people:[
{name:"Cleopatra VII",roundTitle:"Identity 1 · Ptolemaic Egypt",clues:["I ruled in the final generation of Ptolemaic Egypt.","I formed political relationships with Julius Caesar and later Mark Antony.","My defeat after the Battle of Actium came shortly before Egypt became a Roman province."],options:["Hatshepsut","Cleopatra VII","Nefertiti","Zenobia"],answer:1,explain:"Cleopatra VII was the last active ruler of Ptolemaic Egypt before Roman annexation."},
{name:"Mansa Musa",roundTitle:"Identity 2 · Mali",clues:["I ruled a major West African empire in the 14th century.","My pilgrimage to Mecca became famous for displays of wealth.","My reign is associated with Mali's gold wealth and the prominence of Timbuktu."],options:["Sundiata Keita","Mansa Musa","Askia Muhammad","Shaka Zulu"],answer:1,explain:"Mansa Musa's reign brought Mali extraordinary visibility across North Africa and the wider Islamic world."},
{name:"Genghis Khan",roundTitle:"Identity 3 · Steppe Empire",clues:["I united many Mongol groups under my leadership.","My armies created the foundation of the largest contiguous land empire in history.","My birth name is commonly given as Temüjin."],options:["Kublai Khan","Genghis Khan","Tamerlane","Attila"],answer:1,explain:"Genghis Khan united Mongol forces and launched the conquests that created the Mongol Empire."},
{name:"Elizabeth I",roundTitle:"Identity 4 · Tudor England",clues:["I ruled England for more than four decades in the 16th century.","My reign included the defeat of the Spanish Armada in 1588.","I was the daughter of Henry VIII and Anne Boleyn."],options:["Mary I","Elizabeth I","Mary, Queen of Scots","Anne"],answer:1,explain:"Elizabeth I ruled England from 1558 to 1603 during a period of major religious, maritime, and political change."},
{name:"Shaka",roundTitle:"Identity 5 · Southern Africa",clues:["I became a powerful Zulu leader in the early 19th century.","My rule is associated with military reorganization and expansion.","My kingdom became a major political force in southeastern Africa."],options:["Shaka","Cetshwayo","Dingane","Moshoeshoe I"],answer:0,explain:"Shaka transformed the Zulu kingdom into a powerful regional state during the early 1800s."}
],
closing:"Leadership is always larger than biography. Rulers act through institutions, armies, economies, beliefs, advisers, rivals, and communities.",
takeaways:["Geography shapes leadership choices.","Military success does not explain every form of power.","Leaders inherit institutions as well as create them.","Later legend can simplify complicated historical records."]
};