window.CASE_FILE_CONFIG={
title:"The Black Death Case",caseNumber:"05",location:"Europe · 1347–1351",
brief:"Beginning in the late 1340s, plague swept through connected regions of Europe, Asia, and North Africa, killing on an enormous scale. Medieval observers did not know the bacterium that caused it, and the pandemic transformed labor, law, belief, and daily life.",
question:"What best explains both the spread of the Black Death and its enormous social impact?",
assignment:"Work across biology, trade, movement, mortality, and law. Separate medieval explanations from evidence available through modern science and historical records.",
midCaseTwist:{icon:"🦠",title:"The Case Changes After the Deaths",text:"This is not only a disease-spread case. Once large numbers of people died, labor became scarcer, wages came under pressure, and governments responded with new rules. The pandemic changed society as well as population."},
crossExam:{question:"Which explanation best integrates the scientific and historical evidence?",choices:["A bacterial plague moved through connected human-animal and trade networks, and mass mortality then disrupted labor and institutions.","The disease spread only because people believed in supernatural punishment.","The Black Death affected one isolated city and had little economic impact.","No biological cause can be identified."],answer:0,explain:"Modern science identifies Yersinia pestis, while historical records show how connected trade routes and severe mortality produced wider social effects."},
closingCaution:"Modern evidence identifies plague as the disease behind the Black Death, but exact transmission patterns varied by place and outbreak. Historical explanations should distinguish well-supported mechanisms from oversimplified single-cause stories.",
evidence:[
{id:"e1",num:"Evidence 01",title:"The Pathogen",date:"Modern scientific evidence",sourceType:"Disease Evidence",text:"The CDC identifies plague as a disease caused by the bacterium Yersinia pestis. Modern studies of medieval remains have detected plague bacteria associated with Black Death burials.",observation:"The pandemic had a biological cause that medieval observers could not directly identify.",question:"What does this evidence change?",choices:["It gives modern historians a biological explanation unavailable to medieval observers.","It proves medieval medicine understood bacteria.","It shows the Black Death was imaginary.","It means historical records are unnecessary."],answer:0,explain:"Scientific evidence answers questions that written medieval sources could not."},
{id:"e2",num:"Evidence 02",title:"Ships, Ports, and Trade Routes",date:"Spread · 1347 onward",sourceType:"Movement Evidence",text:"Historical accounts place plague reaching Mediterranean ports in 1347 and moving rapidly through established trade networks. Ships, goods, people, rodents, and fleas were all part of highly connected commercial systems.",observation:"The same networks that moved wealth and information could also move disease.",question:"What does this suggest about the speed of spread?",choices:["Connectivity helped carry plague between regions.","Trade routes prevented disease movement.","Only rural isolation spread the disease.","Ships played no role in medieval exchange."],answer:0,explain:"Dense trade networks linked distant communities and accelerated movement of people, animals, and pathogens."},
{id:"e3",num:"Evidence 03",title:"More Than One Form of Plague",date:"Disease mechanism",sourceType:"Medical Evidence",text:"Plague can appear in bubonic, septicemic, and pneumonic forms. Fleas associated with infected rodents are an important route of transmission, while pneumonic plague can spread through respiratory droplets.",observation:"A single simple transmission story cannot explain every case or outbreak.",question:"What is the best historical interpretation?",choices:["Plague transmission could involve multiple biological pathways.","Every case spread in exactly the same way.","The disease was never contagious.","Only weather explains transmission."],answer:0,explain:"Multiple disease forms make a one-mechanism explanation too simple."},
{id:"e4",num:"Evidence 04",title:"Britain Is Hit in 1348",date:"Historical record · England",sourceType:"Chronicle + Archive",text:"The National Archives notes that the second plague pandemic reached Britain in 1348 and caused devastating effects that continued through later outbreaks.",observation:"The pandemic moved across political borders and persisted beyond one wave.",question:"What does this tell us about scale?",choices:["The Black Death was part of a much wider pandemic, not a single local event.","The outbreak stayed in one port.","England was unaffected.","The pandemic ended immediately after arrival."],answer:0,explain:"The record shows both geographic spread and long-term recurrence."},
{id:"e5",num:"Evidence 05",title:"The Statute of Labourers",date:"Law · England, 1351",sourceType:"Legal Record",text:"After severe population losses, England's Statute of Labourers tried to restrict rising wages, control movement of workers, and stabilize a disrupted labor market.",observation:"Mass mortality altered bargaining power and forced governments to respond.",question:"What does this law reveal?",choices:["The pandemic had major economic and labor consequences.","The plague had no effect on employment.","Workers became more abundant after mass mortality.","Government ignored labor disruption."],answer:0,explain:"Legal responses are evidence of how deeply mortality affected the economy."},
{id:"e6",num:"Evidence 06",title:"Repeated Waves",date:"Long-term pattern · 14th century onward",sourceType:"Population History",text:"The Black Death was followed by repeated plague outbreaks. Some regions lost a very large share of their population, and recovery took generations.",observation:"The social effects were not limited to one frightening year.",question:"Why do repeated waves matter?",choices:["They deepened demographic and economic disruption over time.","They prove the first outbreak had no effect.","They made labor markets completely stable.","They mean plague disappeared by 1350 everywhere."],answer:0,explain:"Repeated outbreaks helped make plague a long-term historical force rather than a single episode."}
],
theories:[
{id:"network",title:"Connected Disease Network + Social Shock",desc:"Plague moved through connected ecological and trade systems; mass mortality then transformed labor and institutions.",strong:["e1","e2","e3","e4","e5","e6"],weak:[],summary:"This theory best integrates biological evidence, trade connectivity, multiple transmission routes, large-scale mortality, legal response, and repeated outbreaks."},
{id:"supernatural",title:"Supernatural Punishment Was the Cause",desc:"The Black Death spread because medieval religious explanations correctly identified its mechanism.",strong:[],weak:["e1","e2","e3"],summary:"Religious explanations are historically important evidence of medieval belief, but they do not match modern biological evidence for the disease mechanism."},
{id:"single-route",title:"One Transmission Route Explains Everything",desc:"Every plague case spread through exactly one pathway.",strong:["e2"],weak:["e3"],summary:"Fleas and rodents were important, but plague can also appear in forms with different transmission patterns."},
{id:"local",title:"Mostly a Local European Event",desc:"The Black Death was a contained regional outbreak with limited long-term effects.",strong:[],weak:["e2","e4","e5","e6"],summary:"The geographic spread, repeated waves, and economic consequences conflict with a narrowly local explanation."}
],
sources:[
{label:"CDC — About Plague",url:"https://www.cdc.gov/plague/about/index.html"},
{label:"UK National Archives — Plague",url:"https://www.nationalarchives.gov.uk/explore-the-collection/explore-by-time-period/early-modern/plague/"},
{label:"Swedish History Museum — The Black Death",url:"https://historiska.se/en/explore-history/history-hub/the-black-death/"}
]};