window.ESCAPE_CONFIG={
title:"Escape the Pyramid",brief:"You are inside a royal burial complex where each sealed chamber opens only if you interpret the evidence correctly. The challenge is not fantasy hieroglyphics—it is a history-and-archaeology escape built around what tombs reveal about ancient Egyptian society.",
objectiveTitle:"Unlock the Burial Route",objective:"Solve four historical locks, recover four evidence items, then use them to open the final chamber.",
stages:[
{type:"choice",title:"The Offering Chamber",scene:"A wall scene shows food, vessels, and servants bringing goods toward the tomb owner.",clueTitle:"Clue: Why Leave Offerings?",clue:"Ancient Egyptian burial practices reflected beliefs about an afterlife. Tomb goods, food offerings, and ritual texts were intended to support the deceased beyond death.",hint:"The lock asks what the offerings tell us about belief—not whether people expected the objects to be used in ordinary daily life.",question:"What is the best interpretation of the offerings?",choices:["They reflect belief that the deceased needed continued support in the afterlife.","They were random decorations with no religious meaning.","They prove only kings believed in an afterlife.","They were placed there mainly for later tourists."],answer:0,wrong:"Focus on what burial goods reveal about Egyptian beliefs concerning death and the afterlife.",danger:10,reward:{icon:"🏺",item:"Offering Vessel",note:"Evidence of funerary belief and ritual."},explain:"Burial goods and offerings are strong evidence that Egyptians expected continued existence after death."},
{type:"code",title:"The Calendar Lock",scene:"A carved panel describes the annual Nile flood and the agricultural cycle.",clueTitle:"Clue: Three Seasons",clue:"The ancient Egyptian civil calendar divided the year into three main seasons tied to the Nile and farming: Akhet (inundation), Peret (growing), and Shemu (harvest).",hint:"The lock wants the number of main agricultural seasons.",question:"Enter the number of main seasons.",answer:"3",numeric:true,placeholder:"Enter number",wrong:"Count the named seasons in the clue.",danger:10,reward:{icon:"🌊",item:"Nile Calendar Seal",note:"Shows how river cycles structured life."},explain:"Three major seasons organized the agricultural year around the Nile's cycle."},
{type:"sequence",title:"The Mummification Passage",scene:"Four panels depict steps associated with preparing a body for burial.",clueTitle:"Clue: Preservation Before Burial",clue:"Elite mummification involved removing moisture, treating and wrapping the body, and placing it in coffins before burial rituals were completed.",hint:"Put the process in a logical order from preparation to final burial placement.",question:"Tap the stages in order.",items:["Dry the body with natron","Wrap the body in linen","Place the mummy in a coffin","Complete burial placement in the tomb"],answer:[0,1,2,3],wrong:"Think from physical preservation to final placement.",danger:12,reward:{icon:"🧵",item:"Linen Wrapping",note:"Evidence of preservation practices."},explain:"Preservation and wrapping preceded placement in coffins and the final burial context."},
{type:"choice",title:"The Workers' Corridor",scene:"The final passage asks who actually built and maintained royal tombs.",clueTitle:"Clue: Deir el-Medina",clue:"Archaeological and written evidence from Deir el-Medina documents a community of skilled workers who constructed and decorated royal tombs in the Valley of the Kings.",hint:"The evidence points to organized skilled labor, not the popular movie stereotype.",question:"What does Deir el-Medina evidence show?",choices:["Royal tombs were built by organized communities of skilled workers.","Every pyramid and tomb was built only by enslaved foreigners.","No written records of tomb workers survive.","Royal tombs were built without specialized labor."],answer:0,wrong:"Use the archaeological and documentary evidence in the clue.",danger:12,reward:{icon:"🛠️",item:"Worker's Mark",note:"Evidence of skilled labor communities."},explain:"The workers of Deir el-Medina left unusually rich records of labor, family life, disputes, and tomb construction."}
],
finalLock:{icon:"🚪",question:"Which conclusion best connects all four clues?",choices:["Egyptian tombs reveal links among religion, environment, skilled labor, and social organization.","Tombs tell historians nothing beyond the names of kings.","Every Egyptian had the same burial resources as a pharaoh.","The Nile had no connection to Egyptian society."],answer:0,wrong:"Think about what each recovered item represents.",explain:"The tomb works as historical evidence because it connects belief, environment, labor, craft, and social hierarchy."},
closing:"You escaped by reading the pyramid as evidence. Ancient Egyptian monuments are not just spectacular buildings; they are records of belief, labor, technology, environment, and power.",
takeaways:["Burial goods reveal religious beliefs.","The Nile structured agriculture and time.","Mummification was a complex preservation process.","Skilled labor communities helped build royal tombs."],
sources:[{label:"British Museum — Ancient Egypt",url:"https://www.britishmuseum.org/collection/galleries/egyptian-sculpture"},{label:"Met Museum — Egyptian Art",url:"https://www.metmuseum.org/about-the-met/collection-areas/egyptian-art"}]
};